### ISSUE TITLE
Exlude For selected extensions

### ISSUE THREAD

**Issue by CrypticCus** [ikas-mc/ContextMenuForWindows11#10]
This is .lnk ext. There are no commands for it in my preset. So I need exlude for selected extensions options to exlude .lnk files...

Or for situations like this, menu should be not visible. When matchfolder is not selected and extension list doesn't include .lnk.

When pressed button. it just prompts the file path like an error.
![image](https://user-images.githubusercontent.com/93516630/141844639-1a777164-9da4-471d-8829-4d3cec4bcc5d.png)
![image](https://user-images.githubusercontent.com/93516630/141845075-6c5b68f6-2707-4c36-876f-903ffb50576f.png)

**Comment by lastpust** [comment]
i second to this. it would be great to not to see if its not doing anything

**Comment by ikas-mc** [comment]
Added hidden(no sub menu)
