### ISSUE TITLE
引号加的位置有问题：处理多个文件时，如果其中一个文件包含空格，会无法运行

### ISSUE THREAD

**Issue by MMMMMoris** [ikas-mc/ContextMenuForWindows11#102]
# 直接上配置文件

![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/63332824/410ff7dc-84f0-4aa7-8d25-45934a9cc4dd)

```
{
  "title": "Calculate MD5",
  "exe": "PWSH",
  "param": "-noexit -Command Get-FileHash -LiteralPath \\\"{path}\\\" -Algorithm MD5 | format-list",
  "icon": "\"C:\\Users\\moris\\Pictures\\Elements\\icon\\DIY\\sign\\hash\\NUM\\icon\\32x32\\MD5_32x32.ico\"",
  "index": 3,
  "acceptDirectory": false,
  "acceptExts": "*",
  "acceptFileFlag": 1,
  "acceptFileRegex": "",
  "acceptMultipleFilesFlag": 2,
  "pathDelimiter": ",",
  "paramForMultipleFiles": "-noexit -Command Get-FileHash -LiteralPath {path} -Algorithm MD5 | format-list"
}
```
多个**不含空格**的文件可以计算校验和，**单个含空格**或者**单个不含空格**的文件也可以计算，但是当文件数量为两个及以上，而且其中有**任一文件名包含空格**的时候，如下图

![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/63332824/b14c60ce-3912-4bd4-92f3-89cdaae7d179)

会报错如下

![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/63332824/09594a8c-13ef-4e52-819f-233faad2fc8d)

看起来像是在处理多个文件时，如果其中一个文件包含空格，这个含有空格的文件实际上没有被加上引号，或者说引号加的位置不对，并没有加在每一个文件名字符串两端，导致了这个错误。

以下是 MenuDebug 的结果

![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/63332824/5add3bf1-77bf-4328-a1b5-972ca05550fa)

这个看起来一切正常。这个结果如果直接放到 PowerShell 里面也能正常运行，但是使用右键菜单的就是没法运行

我也不知道是不是我的配置写漏或者写错了什么导致的，我研究了一晚上，只能得出这个结论了。大佬如果发现这是个 bug 的话，麻烦修复下，辛苦了。

**Comment by MMMMMoris** [comment]
# 现在我将配置文件修改为如下了

![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/63332824/5114c3ad-b6f9-4b1f-9fda-44a74599d8b7)

```
{
  "title": "Calculate MD5",
  "exe": "PWSH",
  "param": "-noexit -Command Get-FileHash -LiteralPath \\\"{path}\\\" -Algorithm MD5 | format-list; “MD5 Checksum finished. Press any key to exit...”; [Console]::Readkey() | Out-Null; exit",
  "icon": "\"C:\\Users\\moris\\Pictures\\Elements\\icon\\DIY\\sign\\hash\\NUM\\icon\\32x32\\MD5_32x32.ico\"",
  "index": 3,
  "acceptDirectory": false,
  "acceptExts": "*",
  "acceptFileFlag": 1,
  "acceptFileRegex": "",
  "acceptMultipleFilesFlag": 2,
  "pathDelimiter": ",",
  "paramForMultipleFiles": "-noexit -Command Get-FileHash -LiteralPath \"{path}\" -Algorithm MD5 | format-list; “MD5 Checksum finished. Press any key to exit...”; [Console]::Readkey() | Out-Null; exit"
}
```
控制台不会再一闪而过了，多个不含空格的文件可以计算校验和，单个含空格或者不含空格的文件也可以计算，但是当文件书为两个及以上，而且其中有文件包含空格的时候，如下图

![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/63332824/b14c60ce-3912-4bd4-92f3-89cdaae7d179)

还是会报错如下

![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/63332824/09594a8c-13ef-4e52-819f-233faad2fc8d)

**Comment by MMMMMoris** [comment]
开源部分没有包含 customeContextMenuDebug.exe 的源码吗？会不会是主程序和 customeContextMenuDebug.exe 的解析方式不一样？后者可能做了些许改进？

**Comment by ikas-mc** [comment]
{
    "title": "Calculate MD5",
    "exe": "PWSH",
    "param": "-noexit -Command Get-FileHash -LiteralPath \\\"{path}\\\" -Algorithm MD5 | format-list",
    "icon": "\"C:\\Users\\moris\\Pictures\\Elements\\icon\\DIY\\sign\\hash\\NUM\\icon\\32x32\\MD5_32x32.ico\"",
    "index": 3,
    "acceptDirectory": false,
    "acceptExts": "*",
    "acceptFileFlag": 1,
    "acceptFileRegex": "",
    "acceptMultipleFilesFlag": 2,
    "pathDelimiter": "\\\",\\\"",
    "paramForMultipleFiles": "-noexit -Command Get-FileHash -LiteralPath \\\"{path}\\\" -Algorithm MD5 | format-list"
}

**Comment by MMMMMoris** [comment]
> ```js
> {
>     "title": "Calculate MD5",
>     "exe": "PWSH",
>     "param": "-noexit -Command Get-FileHash -LiteralPath \\\"{path}\\\" -Algorithm MD5 | format-list",
>     "icon": "\"C:\\Users\\moris\\Pictures\\Elements\\icon\\DIY\\sign\\hash\\NUM\\icon\\32x32\\MD5_32x32.ico\"",
>     "index": 3,
>     "acceptDirectory": false,
>     "acceptExts": "*",
>     "acceptFileFlag": 1,
>     "acceptFileRegex": "",
>     "acceptMultipleFilesFlag": 2,
>     "pathDelimiter": "\\\",\\\"",
>     "paramForMultipleFiles": "-noexit -Command Get-FileHash -LiteralPath \\\"{path}\\\" -Algorithm MD5 | format-list"
> }
> ```

Ok，收到，非常感谢。应该早点提交 ISSUE 的，弄了一整晚。

**Comment by ikas-mc** [comment]
ps这个多重转义反直觉，其它的软件就很容易

**Comment by MMMMMoris** [comment]
作者有空可以把这条加到脚本例子里面

**Comment by ikas-mc** [comment]
👌👌
