### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by xgdgsc** [ikas-mc/ContextMenuForWindows11#103]
Please consider adding arm64 support.

**Comment by ikas-mc** [comment]
There is no arm64 to test, but I will try to compile an arm64 installation package first

**Comment by xgdgsc** [comment]
Thanks. I have a group chat of people willing to test,

**Comment by ikas-mc** [comment]
test packages
https://github.com/ikas-mc/ContextMenuForWindows11/actions/runs/7329203658

**Comment by xgdgsc** [comment]
No menu after adding item. Related to https://github.com/ikas-mc/ContextMenuForWindows11/issues/96 ?

**Comment by ikas-mc** [comment]
X64 is the same as ARM64's project configuration. If it still doesn't work after completely uninstalling and restarting the system, nothing i can do

**Comment by ikas-mc** [comment]
the latest build version. I tested it with the arm64 virtual machine and it is already working properly.

https://github.com/ikas-mc/ContextMenuForWindows11/actions/runs/9746424756

use this package
ContextMenuCustom-CMC_DEV_RELEASE-ARM64

**Comment by iKineticate** [comment]
> the latest build version. I tested it with the arm64 virtual machine and it is already working properly.
> 
> https://github.com/ikas-mc/ContextMenuForWindows11/actions/runs/9746424756
> 
> use this package ContextMenuCustom-CMC_DEV_RELEASE-ARM64

I tested it, and it runs perfectly🥰

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.5.3.0
