### ISSUE TITLE
Specify different icons for light and dark mode

### ISSUE THREAD

**Issue by jwortmann** [ikas-mc/ContextMenuForWindows11#104]
The icons for the context menu items which are built-in (from Windows) use different colors in light and dark mode. I created new icons for my custom menu entry, that match the style from the built-in icons. But there is no way to use different icons for the different modes, so at the moment I have to decide to either always use the dark icon, or always use the light icon.

![ContextMenu](https://github.com/ikas-mc/ContextMenuForWindows11/assets/6579999/ed883ce9-5d4d-4188-8f4d-f586f52a44e7)

Would it be possible to add an option to specify different icons, dependent on whether light or dark mode is currently active?

My current config:
```json
{
    "title": "Mit Sublime Text öffnen",
    "exe": "\"C:\\Program Files\\Sublime Text\\sublime_text.exe\"",
    "param": "\"{path}\"",
    "icon": "\"C:\\Icons\\sublime_text_dark.ico\"",
    "index": 0,
    "acceptDirectory": false,
    "acceptExts": "*",
    "acceptFileFlag": 1,
    "acceptFileRegex": "",
    "acceptMultipleFilesFlag": 0,
    "pathDelimiter": "",
    "paramForMultipleFiles": ""
}
```

**Comment by ikas-mc** [comment]
a new config item needs to be added, will add in the future

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.0.0.0
