### ISSUE TITLE
Dude, Your Free Trail On MS Store... Has Gone.

### ISSUE THREAD

**Issue by skycat2216** [ikas-mc/ContextMenuForWindows11#105]
And because of it, All free installation is unable to work now.

I appreciated your work, So I'll compile it my self now.
And Thank You for creating this impressive work.

**Comment by ikas-mc** [comment]
?
What happened? I tested it and it's all okay.

**Comment by skycat2216** [comment]
I...fu[REDACTED].

I just found a M$ store bug.
If somebody get into store with site and is not logged in, M$ store will not shows the free trail button
Thanks for replying.
