### ISSUE TITLE
Add the TortoiseGit menu

### ISSUE THREAD

**Issue by Anson15** [ikas-mc/ContextMenuForWindows11#106]
Trying to make the menu for TortoiseGit like the image but not sure what param need to add 
![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/61965446/c3aaffa6-8d44-424c-b35d-5bf5318a34b1)

(The image shown above is the context menu show in Show More Option)

**Comment by ikas-mc** [comment]
TortoiseGit already supports new context menus
```
= Release 2.15.0 =

   ...
   Added a button to register the win11 context menu for the current user in TortoiseGit settings on the Windows 11 contextmenu page
```

**Comment by Anson15** [comment]
Tried the Register Context Menu button, but it just show the Package Registered then nothing happen to the context menu.
Computer restart but still cannot see the TortoiseGit in context menu.

**Comment by ikas-mc** [comment]
It may be bug
