### ISSUE TITLE
Ability to do character substitution for the {name}

### ISSUE THREAD

**Issue by benze** [ikas-mc/ContextMenuForWindows11#107]
I wanted to create a context shortcut to send a file by Outlook.  However, to use the CLI and specify a subject or body with the filename requires using %20 instead of spaces in the filename (essentially URL encoded).

Any ability to do standard bash-style character replacement in the {} would be great.  For example: {name// /%20}

**Comment by ikas-mc** [comment]
Scripts are recommended
