### ISSUE TITLE
添加NV控制面板

### ISSUE THREAD

**Issue by VwEl** [ikas-mc/ContextMenuForWindows11#109]
怎么才能启动nvcplui.exe，一直没成功
{"title":"NVIDIA Control Panel","exe":"\"C:\\Program Files\\WindowsApps\\NVIDIACorp.NVIDIAControlPanel_8.1.964.0_x64__56jybvy8sckqj\\nvcplui.exe\"","param":"\"{path}\"","icon":"\"C:\\Program Files\\WindowsApps\\NVIDIACorp.NVIDIAControlPanel_8.1.964.0_x64__56jybvy8sckqj\\NvStTest.exe\",0","index":0,"acceptDirectory":true,"acceptExts":"","acceptFileFlag":0,"acceptFileRegex":"","acceptMultipleFilesFlag":0,"pathDelimiter":"","paramForMultipleFiles":""}

**Comment by ikas-mc** [comment]
现在nv面板是打包应用,类似uwp.所以直接打开exe不行.需要使用特殊的打开方式
---
exe: 
explorer.exe 
param:
shell:AppsFolder\NVIDIACorp.NVIDIAControlPanel_56jybvy8sckqj!NVIDIACorp.NVIDIAControlPanel

``` json
{
    "title": "nvcplui.exe",
    "exe": "explorer.exe ",
    "param": "shell:AppsFolder\\NVIDIACorp.NVIDIAControlPanel_56jybvy8sckqj!NVIDIACorp.NVIDIAControlPanel",
    "icon": "\"C:\\Program Files\\WindowsApps\\NVIDIACorp.NVIDIAControlPanel_8.1.964.0_x64__56jybvy8sckqj\\nvcplui.exe\",0",
    "index": 0,
    "acceptDirectory": true,
    "acceptExts": "",
    "acceptFileFlag": 0,
    "acceptFileRegex": "",
    "acceptMultipleFilesFlag": 0,
    "pathDelimiter": "",
    "paramForMultipleFiles": ""
}

```
