### ISSUE TITLE
Match Folder not working on 22000.348

### ISSUE THREAD

**Issue by CrypticCus** [ikas-mc/ContextMenuForWindows11#11]
Match Folder not working on 22000.348, menu not visible on folders and desktop... using latest version of win11 and custommenuforwindows11

![image](https://user-images.githubusercontent.com/93516630/143498234-de2876dd-d5aa-4938-adf9-581c4e979495.png)

**Comment by ikas-mc** [comment]
😟 I tested it on version 22000.348, everything is ok
![2021-11-26 215727](https://user-images.githubusercontent.com/65895428/143591793-73dcc941-f9e3-479f-b730-695ef636cdd2.png)

**Comment by CrypticCus** [comment]
retested on fresh virtual machine. did not worked. maybe your test environment is buggy again.

**Comment by CrypticCus** [comment]
Tested on fresh machine, i tihnk your environments are not healthy to test things. its not working.

![image](https://user-images.githubusercontent.com/93516630/143598241-ac602a85-6cca-4e22-8087-2f10b18d1a54.png)
