### ISSUE TITLE
关于菜单与配置文件命名的问题

### ISSUE THREAD

**Issue by vicenteyu** [ikas-mc/ContextMenuForWindows11#110]
![screenshot-20240127-002937](https://github.com/ikas-mc/ContextMenuForWindows11/assets/1539280/3a6c573d-5c74-4653-97d1-12a8daa4871c)
配置文件生成后，名称不会更随Title变更，挺让人困惑的。
建议命名改为：Id_Title.json，Id使用Guid，修改Title同时对配置文件进行重命名。

**Comment by ikas-mc** [comment]
这个主要是因为ui本质不是必须的,文件名管理权交给用户自行处理.(以前的版本可以根据文件名排序)
后续可以加个开关是否同步

**Comment by ikas-mc** [comment]
加入了修改文件名支持.
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.0.0.0
