### ISSUE TITLE
设置了扩展名，但无扩展名的文件也会被匹配。

### ISSUE THREAD

**Issue by vicenteyu** [ikas-mc/ContextMenuForWindows11#111]
![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/1539280/e607456a-1a9c-42dd-888a-7509cc5880cd)
![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/1539280/28c1f36e-e417-4aa0-8580-25d63d897f59)

**Comment by vicenteyu** [comment]
与 #89 是相同的问题，重复了。

**Comment by ikas-mc** [comment]
是的,主要还是对旧版本的兼容处理
文件如果没有扩展名,但是有时候也期望打开,后面考虑加上配置开关

**Comment by ikas-mc** [comment]
与https://github.com/ikas-mc/ContextMenuForWindows11/issues/89合并
