### ISSUE TITLE
Feature request: customize top level menu icon

### ISSUE THREAD

**Issue by ddomingos-encora** [ikas-mc/ContextMenuForWindows11#113]
Hi, it is possible to specify the top level menu icon? If not, would it be possible to add in a future release?
I did not find anyone talking about this in the issues and I found only the option to specify the subentries icons. Thanks

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.0.0.0
