### ISSUE TITLE
最新版的win11好像失效了

### ISSUE THREAD

**Issue by Anmours** [ikas-mc/ContextMenuForWindows11#115]
昨天上午使用还是正常的，下午发现右键中没有我自定义的按钮了，我不确定是否自动更新导致的，我已试过重新创建菜单并且重启系统，都无效。
![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/76721799/417946ef-0860-43f8-89f6-909430cd95cd)

**Comment by fengjch127** [comment]
duped to #96

**Comment by lbyisme** [comment]
老哥解决了吗

**Comment by bycore** [comment]
yes, I discovered that I've encountered the same issue myself.

**Comment by Anmours** [comment]
> duped to #96

The computer has been restarted n times, but none of them are effective. I found out it's an issue with software updates in the Microsoft Store

**Comment by Anmours** [comment]
> 老哥解决了吗

和系统没关系，我卸载了最近的系统更新还是无效。
后面我发现是微软商店更新的问题
你装的是微软商店那个中文版的吧  卸载了重装英文版的。我看微软商店历史更新记录那个中文版的29号自动更新了，应该是那个问题。我换成英文版的没问题了

**Comment by Anmours** [comment]
> yes, I discovered that I've encountered the same issue myself.

[引用已回复的消息](https://github.com/ikas-mc/ContextMenuForWindows11/issues/115#issuecomment-2028581727)

**Comment by ikas-mc** [comment]
经过测试，最新测试与正式的windows均没有问题……

我没有发布过中文版，商店版本与github是一致的，只有英文版本

**Comment by lbyisme** [comment]
> 软商店历史更新记录那个中文版的29号自动更新了，应该是那个软件更新的问题。我换成英文版的没问题了（中文版卸载了在搜搜不到了。

好的谢谢

**Comment by Anmours** [comment]
> 经过测试，最新测试与正式的windows均没有问题……
> 
> 我没有发布过中文版，商店版本与github是一致的，只有英文版本

之前微软商店有个中文版，就叫“自定义右键菜单” ，可能是三方汉化的，现在搜不到了。 现在换成官方版无问题了~

**Comment by ikas-mc** [comment]
好吧..
因为我自己多台电脑(正式,测试win11)在用,如果更新有问题,我基本就会发现了
那就先关闭了
