### ISSUE TITLE
UWP怎么去添加呀？好像只能添加exe包。。或者说UWP怎么实现添加到一级菜单？ 救命！

### ISSUE THREAD

**Issue by lvle666** [ikas-mc/ContextMenuForWindows11#117]

**Comment by ikas-mc** [comment]
uwp可以添加,不过uwp分为多种情况..
1.如果uwp提供了exe别名,那么直接填写别名就行了,别名可以在设置>高级应用设置>应用执行别名 中查看
2.支持启动协议,直接使用协议
3.如果没有别名,比较麻烦,需要知道包的一些信息,explorer.exe shell:AppsFolder\包信息
可以参考 zhuanlan.zhihu.com/p/574487808 其中2与4方案

3.如果需要传递参数,一般需要uwp本身支持,通常使用1,2来传递参数

**Comment by lvle666** [comment]
十分感谢
