### ISSUE TITLE
Error Code 0x803F8001While Installing

### ISSUE THREAD

**Issue by someone132s** [ikas-mc/ContextMenuForWindows11#119]
When I finished installed the app and tyied to launch it, the error window pops with following texts

'Custom Context Menu is currently not available in your account. Make sure you are signed in to the Store and try again. Here’s the error code, in case you need it: 0x803F8001'

**Comment by ikas-mc** [comment]
Don't download the store version package from github directly

You can uninstall it first and then download it from the store 

or
uninstall it ，install the github version package

**Comment by ikas-mc** [comment]
store : ...m9vp3t2f55f5t.Msixbundle
github : ContextMenuCustomGithubPackage

**Comment by someone132s** [comment]
thks, i'll try immediately

**Comment by someone132s** [comment]
thks, i finally works
