### ISSUE TITLE
FolderMatch Problem

### ISSUE THREAD

**Issue by CrypticCus** [ikas-mc/ContextMenuForWindows11#12]
It seems OneDrive component removal causes this issue. I edit my OS with NTLite,  After my tests i found out it was about OneDrive removal. Take a look at what happens when u don't have onedrive in your system. that depency looks unneeded for your software....

I will also contact to NTLite's dev for potential bug on onedrive removal. But this error started happening in v1.6.0 without any OS changes. I didn't have onedrive before too.

**Comment by CrypticCus** [comment]
yes when i install onedrive. menu comes back.
![image](https://user-images.githubusercontent.com/93516630/143676327-c31e677c-314e-4172-81eb-a874733a65d8.png)

when i uninstall onedrive, menu is dissapeared. i don't think its about my ntlite edit. your software has dependency on onedrive. just why?

**Comment by ikas-mc** [comment]
I think this may be a system problem, this kind of problem is difficult to solve,
because this software uses standard api, what we can do is to implement an interface, and then wait for windows to load.
and the dev version of windows does not directly support the desktop right click, I think Microsoft is still changing this

**Comment by ikas-mc** [comment]
install this test
https://github.com/M2Team/NanaZip

**Comment by CrypticCus** [comment]
hello thank you for your answer,
Yes nanazip context menu works, also winrar context menu works. here is the gif file from windows install to test, speeded up.

i don't think its about system, since previous version works, also it happens on a freshly installed system only thing i did was to clear startmenu because it gets laggy on virtualmachine, and removed onedrive app to show u the issue...

i can also share you the ISO file with only edit is onedrive removal.

here is the gif: https://ibb.co/pdZqZfh
download gif: https://www30.zippyshare.com/v/2F4Xlvpn/file.html

PS: after the video i removed onedrive and custom menu stayed there.

**Comment by ikas-mc** [comment]
It may indeed be some dependency problems,
I am downloading, then I will try to find the problem

**Comment by ikas-mc** [comment]
After testing, it will not load the "dll" at all, even if I use vs debugging 

![26](https://user-images.githubusercontent.com/65895428/143740739-5e52517f-ee3e-4606-9d82-f66e6a80a13f.gif)

**Comment by ikas-mc** [comment]
After multiple use of virtual machine recovery and installation tests,
I found that the computer I am using also has this problem: right click on the desktop does not display the new menu... (including Windows Terminal, my app...)

I uninstalled onedriver and installed the latest version, it fixed the Windows Terminal menu

Then, I installed Windows Terminal on your system and also reproduced the problem

**Comment by ikas-mc** [comment]
![27](https://user-images.githubusercontent.com/65895428/143760742-6f758bf7-5f41-4f89-8e73-80ad6332cbb8.gif)
after install OneDrive
![28](https://user-images.githubusercontent.com/65895428/143761009-06c76e25-bff5-4bd2-88b0-7ec8d977bd03.gif)

🤣🤣🤣🤣🤣🤣🤣🤣

**Comment by CrypticCus** [comment]
soo you can see the problem, it may be windows bug or not i really don't know. maybe we should wait for next windows update or test on the preview versions...

**Comment by ikas-mc** [comment]
Yes...22489 also has this problem...
This is difficult to debug and find the problem.. Need feedback to windows

**Comment by CrypticCus** [comment]
btw this was not happening on build 318. so i think, older windows versions was stable?

**Comment by ikas-mc** [comment]
@CrypticCus 
i download 22000.194 and delete onedrivesetup.exe
test result is:
22000.194 without onedrive  = ok
update to 384 without onedrive = bug
384 with onedrive  installed= ok

**Comment by CrypticCus** [comment]
i get it its a microsoft bug, but still dependency between onedrive and context menu right click is just stupid.

**Comment by CrypticCus** [comment]
BTW another bug its related to you only, it shows as "Open With" when fresly installed
![image](https://user-images.githubusercontent.com/93516630/143791069-f356abcf-7378-47b7-9bde-bac7ae6b0d81.png)

but in settings it says
![image](https://user-images.githubusercontent.com/93516630/143791076-a790b158-4ccb-4fdc-b61b-b8aae5cf8ea8.png)

its fixed after saving or changing menu but still its a bug

**Comment by ikas-mc** [comment]
There are some confusion about the default values.. Change to the same next time

**Comment by CrypticCus** [comment]
Can you also send feedback or this page to the microsoft? i don't think they know about this bug. they never fix things if its not reported.

**Comment by ikas-mc** [comment]
I have I have created an issue
terminal/issues/11839

**Comment by ikas-mc** [comment]
"this was promoted internally to MSFT:37214068. There's not much for us to do here - this seems like a bug firmly in the explorer team's codebase."

**Comment by CrypticCus** [comment]
Quote: "......, it seems the issue was fixed in the 22598.200 build version"
