### ISSUE TITLE
UWP对获取的文件路径无法操作

### ISSUE THREAD

**Issue by lvle666** [ikas-mc/ContextMenuForWindows11#121]
右键菜单打开UWP后，识别为CommandLineLaunch，识别为从命令行打开应用程序，这里只能获取到文件路径，我生成StorageFile对象是没有权限的。能否做到让UWP识别为从文件打开应用程序，这样就可以拿到StorageFile对象。或者是否存在其它方法？

**Comment by lvle666** [comment]
我需要StorageFile对象以进行下一步操作

**Comment by ikas-mc** [comment]
虽然直接StorageFile更加方便,但是应该没有办法控制这种不一致的行为
推荐uwp使用别名,CommandLineLaunch.我自己的其它uwp也都是这样实现
权限可以通过配置broadFileSystemAccess可以解决

**Comment by lvle666** [comment]
嗯嗯，我目前是使用别名然后在CommandLineLaunch拿到文件路径参数，broadFileSystemAccess是高敏感权限，然后我采用的方案是：
1.用户接受broadFileSystemAccess，一切正常执行
2.用户不接受broadFileSystemAccess
   - 直接双击打开文件，或者直接从二级菜单打开，将文件记录FutureAccessList，这样下次从一级菜单打开该文件就避免了权限问题
   - 直接从一级菜单打开文件，复制文件路径到剪贴板，弹出文件选取弹窗，提示用户粘贴路径选择，避免权限问题
   - 在清单中开放访问文档，音乐库，视频库等低敏感权限（考虑中，这会在商店信息中直接显示，部分用户对隐私较为看重）

**Comment by lvle666** [comment]
@ikas-mc  谢谢回复
