### ISSUE TITLE
WPF 应用如何创建这个右击菜单程序实现这个Com组件

### ISSUE THREAD

**Issue by Li-meng-meng** [ikas-mc/ContextMenuForWindows11#123]
我想在WPF实现这个Com组件有什么办法嘛，或者WPF应用有没有办法在win11菜单上增加新的菜单

**Comment by ikas-mc** [comment]
主要是[ContextMenuCustomHost](https://github.com/ikas-mc/ContextMenuForWindows11/tree/main/ContextMenuCustom/ContextMenuCustomHost)这个项目,实现一个独立的dll

第一种方式是将wpf打包为msix, https://learn.microsoft.com/zh-cn/windows/msix/packaging-tool/tool-overview 

第二种可以参考https://github.com/notepad-plus-plus/nppShell
