### ISSUE TITLE
 In the parameters, the path to the penultimate folder

### ISSUE THREAD

**Issue by Sta1917** [ikas-mc/ContextMenuForWindows11#126]
Instead of
C:\Users\Admin\Desktop returns
C:\Users\Admin
I tried "path" and "%~dp0"

In the old menu, the command works correctly
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\_CreateFolderDate\command]
@="\"C:\\TemplatesFolders\\create_folder_date.cmd\" \"%~dp0\""
```
ContextMenuForWindows11 Version: 3.8.0
Windows 11 Pro Build 22621.ni_release.220506-1250

![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/130297685/4b42c068-d4bc-49d1-b71d-55f6f839a5f2)

**Comment by ikas-mc** [comment]
```json
{
  "title": "New Folder",
  "exe": "F:\\mkdir.cmd",
  "param": " \"{path}\"",
  "icon": "C:\\WINDOWS\\System32\\SHELL32.dll,4",
  "acceptDirectory": false,
  "acceptDirectoryFlag": 7,
  "acceptFile": false,
  "acceptFileFlag": 0,
  "acceptMultipleFilesFlag": 0,
  "index": 0
}

```

mkdir.cmd
```cmd
@echo off
set "ymd=%date:~,4%%date:~5,2%%date:~8,2%"
mkdir %~f1\%ymd%
```


![2024-05-05 044343](https://github.com/ikas-mc/ContextMenuForWindows11/assets/65895428/232a7fbd-817f-4ce4-9b82-db6eeae1d237)
