### ISSUE TITLE
What is the problem with signature failure，What should I pay attention to when signing MSIX

### ISSUE THREAD

**Issue by Li-meng-meng** [ikas-mc/ContextMenuForWindows11#128]
https://github.com/notepad-plus-plus/nppShell  尝试这个方法MSIX签名一直失败，怎么解决这个问题
Error information: "Error: SignerSign() failed." (-2147024885/0x8007000b)

**Comment by ikas-mc** [comment]
大概率是证书的主题与xml文件中的不一致
