### ISSUE TITLE
Not working, samples don't work either

### ISSUE THREAD

**Issue by kirides** [ikas-mc/ContextMenuForWindows11#13]
vscode is installed as "user" and available in `%PATH%` as code.exe

Expected:
Show Entry with "open in vscode" in context menu, after right-clicking any file (tested with `.txt`, `.jpg`, ...)

Actual:
No menu shown

![image](https://user-images.githubusercontent.com/13602143/144101790-49799fe9-1440-442a-a18f-425f13363a3d.png)

----

Repro steps:

Using sample from this repo

`5.open in vscode.json`
```json
{"title":"open in vscode","exe":"code","param":"\"{path}\""}
```

![image](https://user-images.githubusercontent.com/13602143/144100259-753422a3-afa4-45ff-a88b-165528259759.png)

Cache is disabled
![image](https://user-images.githubusercontent.com/13602143/144100427-3a11c628-40cd-4032-9973-839cf96a1b8f.png)

**Comment by ikas-mc** [comment]
Try to restart explorer after installation

add this
[file_test.zip](https://github.com/ikas-mc/ContextMenuForWindows11/files/7633640/file_test.zip)

Open the task manager, observe dllhost.exe, when you right-click,  whether there is such a process  (DllHost.exe" /Processid:{46F650E5-9959-48D6-AC13-A9637C5B3787})




![20211201201259](https://user-images.githubusercontent.com/65895428/144232613-48bacb75-8fad-47e8-a6a7-cff59da02df9.png)

**Comment by kirides** [comment]
Yup. had to restart windows.

just restarting explorer.exe didn't help. Probably some caching...

Sorry for bothering ^^'

**Comment by ikas-mc** [comment]
if there is a bug, you can continue to feedback here
