### ISSUE TITLE
我的扩展包安装上了，注册表已经有对应的信息了，但是没有出现右键菜单

### ISSUE THREAD

**Issue by Li-meng-meng** [ikas-mc/ContextMenuForWindows11#130]
我现在用这个方法：https://github.com/notepad-plus-plus/nppShell 和您这个方法结合，把ContextMenuCustomHost文件中CustomExplorerCommand.cpp：：ReadCommands函数修改了路径，把这个ContextMenuCustomHost库加到了外部包中，我的扩展包安装没问题了，注册表也有对应的信息了，我在custom_commands也添加了一个Json文件，但是还是没有右击菜单，有什么办法知道我哪里了出错了嘛，或者是不是这个方案不可以这样结合。

**Comment by ikas-mc** [comment]
1.是否加载可以查看任务管理器，过滤dlldhost.exe，然后右键的时候，查看是否有uuid一致的新进程
2.使用debugview，然后c++打印日志查看

**Comment by Li-meng-meng** [comment]
谢谢解答，尝试查看任务管理器，没有发现对应的uuid，服务没有启动
有尝试UWP应用只安装不启动程序是不会启动服务，是不是外部包需要运行一下，但是我不知外部包如何运行，或者是否有其他的方法，再次感谢您耐心解答
CustomExplorerCommand.h中的uuid是有调整一致
![清单](https://github.com/ikas-mc/ContextMenuForWindows11/assets/117915981/174752de-5d7c-4b6a-af5e-e948669f8b83)
![uuid](https://github.com/ikas-mc/ContextMenuForWindows11/assets/117915981/51a33994-5ee8-4bd3-9c9a-682a40b6de4a)

**Comment by ikas-mc** [comment]
我参照这个,尝试了一下,没有问题
https://github.com/microsoft/AppModelSamples/tree/master/Samples/SparsePackages
https://learn.microsoft.com/zh-cn/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps\

```
参阅 StartUp.cs  修改包位置
string sparsePkgPath = @"F:\PhotoStoreDemo_1.0.4.0_x86__8yektv5z29sbg.msix";

```
c#项目中 PhotoStoreDemo.exe.manifest 必须与  AppxManifest.xml  还有签名一致

启动项目, StartUp.cs中会注册msix, 代码可以debug看到注册结果,也可以使用命令查看

 get-appxpackage -name PhotoStoreDemo
```
Name              : PhotoStoreDemo
Publisher         : CN=ikas-mc-dev
Architecture      : Neutral
ResourceId        :
Version           : 1.0.4.0
PackageFullName   : PhotoStoreDemo_1.0.4.0_neutral__8yektv5z29sbg
InstallLocation   : C:\Program Files\WindowsApps\PhotoStoreDemo_1.0.4.0_neutral__8yektv5z29sbg
IsFramework       : False
PackageFamilyName : PhotoStoreDemo_8yektv5z29sbg
PublisherId       : 8yektv5z29sbg
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Developer
Status            : Ok

``

使用 get-appxpackage -name PhotoStoreDemo  | remove-appxpackage 可以卸载msix


源码:
[PhotoStoreDemo.zip](https://github.com/ikas-mc/ContextMenuForWindows11/files/15275769/PhotoStoreDemo.zip)

[PhotoStoreDemo_1.0.4.0_x86__8yektv5z29sbg.zip](https://github.com/ikas-mc/ContextMenuForWindows11/files/15275772/PhotoStoreDemo_1.0.4.0_x86__8yektv5z29sbg.zip)

**Comment by Li-meng-meng** [comment]
有尝试他的方法，不知道是我漏了那一步，这个的写的demo，如果有空的话是否可以把我看看，这个问题我先关闭了，我可能需要仔细看看
https://github.com/Li-meng-meng/SoftwareMenu.git

**Comment by Li-meng-meng** [comment]
谢谢您的耐心解答

**Comment by ikas-mc** [comment]
代码看不到...是不是私有的?

**Comment by Li-meng-meng** [comment]
抱歉忘记改权限了，已经调成公有了

**Comment by ikas-mc** [comment]
@Li-meng-meng 
测试了下,可以显示
```
string externalLocation = @"C:\Users\xxxx\source\repos\SoftwareMenu\SoftwareMenu\bin\Debug\SoftwareMenu.exe";
```
应该是这个地址的问题, 这个地址是dll,exe所在的文件夹

**Comment by Li-meng-meng** [comment]
谢谢，尝试修改，现在正常显示
