### ISSUE TITLE
Allow for URI protocols, 

### ISSUE THREAD

**Issue by Immac** [ikas-mc/ContextMenuForWindows11#131]
For example using URI protocols from Obsidian, or Steam
https://help.obsidian.md/Extending+Obsidian/Obsidian+URI
steam://launch/958400/dialog

**Comment by ikas-mc** [comment]
{
  "title": "Menu-1715519518033",
  "exe": "explorer",
  "param": "quick-look://\"{path}\"",
  "acceptDirectory": false,
  "acceptDirectoryFlag": 7,
  "acceptFile": false,
  "acceptFileFlag": 4,
  "acceptMultipleFilesFlag": 1,
  "index": 0
}

**Comment by Immac** [comment]
> ```json
> {
>   "title": "Menu-1715519518033",
>   "exe": "quick-look://",
>   "param": "",
>   "acceptDirectory": false,
>   "acceptDirectoryFlag": 7,
>   "acceptFile": false,
>   "acceptFileFlag": 4,
>   "acceptMultipleFilesFlag": 1,
>   "index": 0
> }
> ```
> 
> ```json
> {
>   "title": "Menu-1715519518033",
>   "exe": "explorer",
>   "param": "quick-look://\"{path}\"",
>   "acceptDirectory": false,
>   "acceptDirectoryFlag": 7,
>   "acceptFile": false,
>   "acceptFileFlag": 4,
>   "acceptMultipleFilesFlag": 1,
>   "index": 0
> }
> ```

So, I have to do it manually? I mean that's doable, but I meant from the GUI, thanks for the workaround.

**Comment by Immac** [comment]
To anyone wondering I was able to do what I wanted, sort of, I wanted to open an obsidian vault using the context menu, but it seems the protocol just takes paths to files not to vaults, in any case, just with the GUI it was a matter of using quotations around the parameter. Just as an extra, I was not able to use the vault parameter because I can't get just the parent folder's name, it uses the whole path, so I had to use the path directly.
![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/3265190/2909c039-62cd-48d3-ad4a-aed931e523bd)

**Comment by ikas-mc** [comment]
currently a limited number of variables supported, and if it is a complex uri, it is recommended to open it through a script
