### ISSUE TITLE
how to use light/dark icon?

### ISSUE THREAD

**Issue by ghost1372** [ikas-mc/ContextMenuForWindows11#133]
how to use light/dark icon?

**Comment by ikas-mc** [comment]
need to have two custom icons

When the system is light theme, load the icon for light and vice versa

**Comment by ghost1372** [comment]
> need to have two custom icons
> 
> When the system is light theme, load the icon for light and vice versa

hmm... can you show some code?

**Comment by ikas-mc** [comment]
![1](https://github.com/ikas-mc/ContextMenuForWindows11/assets/65895428/14c8c031-d957-425e-beb6-47a66565aee9)

**Comment by ghost1372** [comment]
> ![1](https://private-user-images.githubusercontent.com/65895428/332114636-14c8c031-d957-425e-beb6-47a66565aee9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTkxNzgsIm5iZiI6MTcxNjIxODg3OCwicGF0aCI6Ii82NTg5NTQyOC8zMzIxMTQ2MzYtMTRjOGMwMzEtZDk1Ny00MjVlLWJlYjYtNDdhNjY1NjVhZWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE1Mjc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4Y2I1M2ExNzIwMjhmZGE4NTM0ODUyMDYyMzEyMDBhZTdkYTFhZGU5Yzg4ODIyNTBiODY4NzkyMmZmZDZlMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AoGwC5f_9pKuOWNmLpni1nuwzr8QyYwmxrsAzKALziU)

tnx,
