### ISSUE TITLE
Do not work on Windows11 on Arm 24H2

### ISSUE THREAD

**Issue by MOONOTUS** [ikas-mc/ContextMenuForWindows11#135]
System : Windows 24H2 ( 26100.863 ) 
CPU  : Snapdragon XElite
App version : 5.1.1.0

I installed the application from Microsoft Store, and tried to add an VSCode shortcut into windows context menu, then I found it doesn't works.I tried to run it as administrator、restart it、and restart my computer, and then failed.

**Comment by ikas-mc** [comment]
since there is no arm64 device, it is impossible to determine the problem. Please try the arm64 version in the github action and try to refer to the instructions in the wiki to see if there are logs

**Comment by ikas-mc** [comment]
![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/65895428/cfa15a0e-d181-43f0-b626-e0008595db52)

Please try the latest build version. I tested it with the arm64 virtual machine and it is already working properly.

**Comment by MOONOTUS** [comment]
> ![图像](https://private-user-images.githubusercontent.com/65895428/344870933-cfa15a0e-d181-43f0-b626-e0008595db52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTU3NTgsIm5iZiI6MTcxOTg5NTQ1OCwicGF0aCI6Ii82NTg5NTQyOC8zNDQ4NzA5MzMtY2ZhMTVhMGUtZDE4MS00M2YwLWI2MjYtZTAwMDg1OTVkYjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA0NDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZmJjYjU1ZGJhM2IyNDllMDEwZjUyM2MyMjQ0ZDRiYzFhZGUyNDBjMDM5NGViZGVkOWVmZDBhMDU2MDM0MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F48E5k7_R0faoRhj_5JB40y6YR2eSrBbdWsHnElpx4s)
> 
> 请尝试最新版本。我用 arm64 虚拟机对其进行了测试，它已经正常工作。
> 
> https://github.com/ikas-mc/ContextMenuForWindows11/actions/runs/9746424756
> 
> 使用此包 ContextMenuCustom-CMC_DEV_RELEASE-ARM64

OK I'll do it.

**Comment by MOONOTUS** [comment]
It works correctly, thanks for your hard-working
