### ISSUE TITLE
关于右下角 功能菜单没有对齐的问题

### ISSUE THREAD

**Issue by vicenteyu** [ikas-mc/ContextMenuForWindows11#137]
![screenshot-20240630-214406](https://github.com/ikas-mc/ContextMenuForWindows11/assets/1539280/253052be-168f-48fd-afa8-e27049d00c73)

**Comment by ikas-mc** [comment]
感谢，已经修复，马上action编译下

**Comment by ikas-mc** [comment]
最新构建版本已修复，正式版估计要等一段时间发布
