### ISSUE TITLE
选择图标时，图标文件（.ico）格式错误

### ISSUE THREAD

**Issue by iKineticate** [ikas-mc/ContextMenuForWindows11#138]
正确格式是.ico
![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/115683118/341662ff-f3b1-476a-81c4-14756ed299b6)

**Comment by ikas-mc** [comment]
😹看到了，晚点修复

**Comment by ikas-mc** [comment]
构建版已经修改
