### ISSUE TITLE
Feature Request: Add .ico as icon source

### ISSUE THREAD

**Issue by Cris--** [ikas-mc/ContextMenuForWindows11#140]
There are thousand of icons in .ico format around the web.
Please add as icon source also.

**Comment by ikas-mc** [comment]
this is a bug in the file picker current version, which has been fixed, but not released

However, you can manually paste the icon path

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.5.3.0
