### ISSUE TITLE
Feature Request: Add a simple on/off for an entry

### ISSUE THREAD

**Issue by Cris--** [ikas-mc/ContextMenuForWindows11#141]
Sometimes i'm not final with my context menu entry so we can then simply deactivate an entry.

**Comment by ikas-mc** [comment]
try add later
add a switch to modify the file name ,menu.json -> menu.json.disabled

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.5.3.0
