### ISSUE TITLE
Renew zh-cn language pack/更新语言包

### ISSUE THREAD

**Issue by CommandPrompt-Wang** [ikas-mc/ContextMenuForWindows11#145]
中文语言包的翻译很难懂，我简单调整了一下
但我没法拉取也没法上传
新的中文包下附

It's hard to understand this localization and I tried to make it better.
But i cannot make a pull-requests
The new zh-cn pack is as followed

[zh-CN.json](https://github.com/user-attachments/files/16485341/zh-CN.json)

**Comment by ikas-mc** [comment]
感谢，那个示例中文主要是ai翻译的
后面我会加入一个收集语言得问题单
