### ISSUE TITLE
路径传参不正确

### ISSUE THREAD

**Issue by jangnanyiye** [ikas-mc/ContextMenuForWindows11#146]
好不容易调试好脚本，发现右键时脚本打开路径不对，经过测试后发现总是在父目录打开，我已经无数次确认选择了"{path}"，无数次保存，重启资源管理器还有电脑，但都不能解决问题
![屏幕截图 2024-08-14 191556](https://github.com/user-attachments/assets/aa483824-fd0e-475c-9662-b29585083dea)
![屏幕截图 2024-08-14 192422](https://github.com/user-attachments/assets/10e88a74-f2e9-495e-9f9c-4d28ac16033f)
![屏幕截图 2024-08-14 191643](https://github.com/user-attachments/assets/117bd0ba-8302-4a6e-bd08-de574e434f25)
![屏幕截图 2024-08-14 191749](https://github.com/user-attachments/assets/2a2da414-6862-4ab6-a1cd-2541626e40c3)

**Comment by ikas-mc** [comment]
脚本内部不应该使用%cd%吧,应该去获取传入的第一个参数

为啥用bat中转一次呢，可以直接调用ps

**Comment by jangnanyiye** [comment]
问题解决了，在首行加一个 cd %* 主动接收参数即可
debug后发现参数输出没有问题，那就是传参出问题了，经过摸索尝试了主动接收参数
以下是调试以及输出
![屏幕截图 2024-08-15 085622](https://github.com/user-attachments/assets/1beaf888-aa4a-438c-92c6-bfd93a0adec1)
值得一提的是，如果不加 cd %* ，会出现接收参数但没有完全接收的情况
例如在C:\Users\14368\Downloads\Dism_10.1.1002.1B_Green上右键执行，输出为C:\Users\14368\Downloads\Dism_10.1.1002.1B_Green，提示符会进入C:\Users\14368\Downloads
这看起来是会进入父目录
但是将软件参数改为"{path}\more"后，输出为C:\Users\14368\Downloads\Dism_10.1.1002.1B_Green\more，提示符依旧会进入C:\Users\14368\Downloads，它居然这么聪明，还不上当！
调试过程真让人迷糊啊

**Comment by ikas-mc** [comment]
应该是工作目录 ，调用时会将当前右键的文件父目录作为工作目录
