### ISSUE TITLE
缺失Working Directory功能

### ISSUE THREAD

**Issue by PandaFiredoge** [ikas-mc/ContextMenuForWindows11#153]
不支持自定义工作目录

**Comment by ikas-mc** [comment]
测试版本支持，去action试试

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.5.3.0

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.5.7.0
已支持,如有其它问题,可以开新单
