### ISSUE TITLE
Multiple Menus Not Working

### ISSUE THREAD

**Issue by jacobh12349** [ikas-mc/ContextMenuForWindows11#154]
I have 1 menu that's for all file types, and another menu that's only for image files with ".jpg|.jpeg|.png|.gif|.bmp|.tiff|.ico|.svg|.webp" as the file type for it, and the menu for all files shows, but the menu that's only for image types doesn't show when the menu for all files is enabled, the image menu only shows when I remove the menu that's for all file types, I think the menu for all file types is like overriding the menu for image files.

**Comment by jacobh12349** [comment]
The menu for all file types doesn't even show on image files too

**Comment by ikas-mc** [comment]
tested ,but all work fine


```
{
  "title": "test-all-file",
  "exe": "notepad.exe",
  "param": "\"{path}\"",
  "acceptDirectory": false,
  "acceptDirectoryFlag": 0,
  "acceptFile": false,
  "acceptFileFlag": 4,
  "acceptMultipleFilesFlag": 0,
  "index": 0
}


{
  "title": "tese-images-only",
  "exe": "notepad.exe",
  "param": "\"{path}\"",
  "acceptDirectory": false,
  "acceptDirectoryFlag": 0,
  "acceptFile": false,
  "acceptFileFlag": 3,
  "acceptExts": ".jpg|.jpeg|.png|.gif|.bmp|.tiff|.ico|.svg|.webp",
  "acceptMultipleFilesFlag": 0,
  "index": 0
}

```
right on xxx.png
![1](https://github.com/user-attachments/assets/0ce60ccc-4814-411d-a6aa-21cf30709f7a)

**Comment by jacobh12349** [comment]
```
{"title":"Scan With DIE","exe":"\"C:\\Users\\jacob\\Downloads\\die_win64_portable_3.09_x64\\die.exe\"","param":"\"{name}\"","acceptDirectory":false,"acceptDirectoryFlag":0,"acceptFile":false,"acceptFileFlag":4,"acceptExts":"","acceptMultipleFilesFlag":1,"index":0}

{"title":"Edit","exe":"\"C:\\Users\\jacob\\AppData\\Local\\Microsoft\\WindowsApps\\mspaint.exe\"","param":"\"{name}\"","icon":"\"C:\\Program Files\\WindowsApps\\Microsoft.Paint_11.2406.42.0_x64__8wekyb3d8bbwe\\Assets\\PaintStoreLogo.scale-200.png\"","iconDark":"\"C:\\Program Files\\WindowsApps\\Microsoft.Paint_11.2406.42.0_x64__8wekyb3d8bbwe\\Assets\\PaintStoreLogo.scale-200.png\"","acceptDirectory":false,"acceptDirectoryFlag":0,"acceptFile":false,"acceptFileFlag":3,"acceptExts":".jpg|.jpeg|.png|.gif|.bmp|.tiff|.ico|.svg|.webp","acceptMultipleFilesFlag":0,"index":0}
```

Not for me.
It wouldn't let me take a screenshot while the right click menu was open, so i just did a screen recording of them.

https://github.com/user-attachments/assets/0d19d4ad-ab62-453c-9a9d-ee5db9d856d6

https://github.com/user-attachments/assets/e2214313-a9d8-43ec-a91a-bbb51981f97e

**Comment by jacobh12349** [comment]
I'm also using the -GITHUB zip from the releases of this repo, I don't even know what the differences are between the zip releases here..

**Comment by ikas-mc** [comment]
all package contents are the same, only the package identifier is different (install packages at the same time)

imported your menus, but all work fine 

https://github.com/user-attachments/assets/c9b89e06-7d5d-4472-9b15-e6bde272d86a

more test is needed
can you add a menu with other extensions to match ? (.tes|.xxx)

**Comment by jacobh12349** [comment]
I'm not using a custom menu for the Edit one

**Comment by jacobh12349** [comment]
Do I need to use a menu title for it to show multiple?

**Comment by jacobh12349** [comment]
I have the Menu Title blank in my settings, because i want them to both be on the default context menu

**Comment by jacobh12349** [comment]
or is there anyway i can just make the scan one show on all files except for images?

**Comment by ikas-mc** [comment]
one package can only have one menu ,limited by windows
If there is more than one menu, Windows will change them to submenus
If the title is empty, the default title is used


> Or is there anyway i can just make the scan one show on all files other than images?

use regex, match file names, exclude image exts

**Comment by jacobh12349** [comment]
Ok, i just looked up about excluding certain words in regex, and none of them worked, how do you do it in regex in this?

**Comment by jacobh12349** [comment]
> one package can only have one menu ,limited by windows If there is more than one menu
And ok, i just installed both the dev version of it and the github version of it now, to be able to have multiple menus

**Comment by ikas-mc** [comment]
try this
```regex
^(?!.*\.(jpg|jpeg|png|gif|bmp|tiff|ico|svg|webp)$).+$

```

**Comment by jacobh12349** [comment]
Ok thx that worked, and ya, i dont know that much about regex

**Comment by jacobh12349** [comment]
I guess that's everything working now, so I guess I'll just close this issue now. Thx for the help.
