### ISSUE TITLE
New folder yyyy-mm-dd

### ISSUE THREAD

**Issue by tailerteilor** [ikas-mc/ContextMenuForWindows11#155]
I have the code below in a newfolder.bat file in C:\menu. How to create a menu to generate a command to generate a new folder yyyy-mm-dd with right click?

@echo off
setlocal

rem Obter a data no formato yyyy-mm-dd
for /f "tokens=2 delims==" %%A in ('wmic os get localdatetime /value') do set datetime=%%A
set year=%datetime:~0,4%
set month=%datetime:~4,2%
set day=%datetime:~6,2%

set foldername=%year%-%month%-%day%

rem Criar a pasta com o nome da data
mkdir %foldername%

endlocal

**Comment by ikas-mc** [comment]
use this

menu

```
{
  "title": "New Folder",
  "exe": "F:\\mkdir.cmd",
  "param": " \"{path}\"",
  "icon": "",
  "acceptDirectory": false,
  "acceptDirectoryFlag": 7,
  "acceptFile": false,
  "acceptFileFlag": 0,
  "acceptMultipleFilesFlag": 0,
  "index": 0
}

```

mkdir.cmd

```
@echo off
set "ymd=%date:~,4%%date:~5,2%%date:~8,2%"
mkdir %~f1\%ymd%
```

**Comment by tailerteilor** [comment]
Dont work, but this is ok. Thanks

**New Folder - yyyy-mm-dd.json**
{"title":"New Folder - yyyy-mm-dd","exe":"\"C:\\Windows\\System32\\cmd.exe\"","param":"\"cmd /c copy c:\\menu\\folder.bat \"{path}\" &cd \"{path}\" &folder.bat &del folder.bat\"","icon":"\"C:\\Menu\\folder.bat\",0","acceptDirectory":false,"acceptDirectoryFlag":7,"acceptFile":false,"acceptFileFlag":4,"acceptMultipleFilesFlag":1,"index":0}


**Folder.bat in C:\Menu**
@echo off
setlocal

rem Obter a data no formato yyyy-mm-dd
for /f "tokens=2 delims==" %%A in ('wmic os get localdatetime /value') do set datetime=%%A
set year=%datetime:~0,4%
set month=%datetime:~4,2%
set day=%datetime:~6,2%

set foldername=%year%-%month%-%day%

rem Criar a pasta com o nome da data
mkdir %foldername%

endlocal

**Comment by ikas-mc** [comment]
sorry,I ignored the language format, the name by mkdir.cmd may contain invalid char

u can use **%~f1** to recevie the current folder path 
no need to copy script
```
@echo off
rem Obter a data no formato yyyy-mm-dd
for /f "tokens=2 delims==" %%A in ('wmic os get localdatetime /value') do set datetime=%%A
set year=%datetime:~0,4%
set month=%datetime:~4,2%
set day=%datetime:~6,2%

set foldername=%year%-%month%-%day%

mkdir %~f1\%foldername%
```

**Comment by tailerteilor** [comment]
Thanks! It's faster and more efficient not to have to copy and delete the .bat
