### ISSUE TITLE
Multibyte characters entered in Title are garbled.

### ISSUE THREAD

**Issue by moondoldo** [ikas-mc/ContextMenuForWindows11#16]
(Translate with translation software)
Multibyte characters entered in Title are garbled.
The multibyte characters entered in the Custum Menu Title will be displayed correctly.

In the version 1.5.0.0 introduced in "窓の杜", it looks like the multibyte characters specified in Title are displayed.
https://forest.watch.impress.co.jp/docs/serial/win11must/1368429.html

> 3.Add cacche to optimize menu display speed (Need to build the cache menually)

and is it affecting the display of Title characters?

--------------------------------
Titleに入力したマルチバイト文字が文字化けします
Custum Menu Titleに入力したマルチバイト文字は正常に表示されます

"窓の杜"で紹介されたv1.5.0.0では、Titleに指定したマルチバイト文字が表示されてる様に見える
https://forest.watch.impress.co.jp/docs/serial/win11must/1368429.html

> 3.Add cacche to optimize menu display speed (Need to build the cache menually)

で、Title文字の表示に影響を及ぼしているのではないか？

**Comment by ikas-mc** [comment]
@moondoldo 
After testing, the cache does cause character problems   
please wait

**Comment by ikas-mc** [comment]
![1](https://user-images.githubusercontent.com/65895428/146797096-545bef7e-097a-4aa0-a5e2-9d2bb03ba70e.png)
![2](https://user-images.githubusercontent.com/65895428/146797186-ca2ac986-0323-428e-9080-c2ac938f1806.png)

fixed!

**Comment by moondoldo** [comment]
(Translate with translation software)
I have confirmed that it displays correctly with v1.8.0 of Microsoft Store.
Thank you very much!
--------------------------
Microsoft Store の v1.8.0 で正しく表示できることを確認しました
ありがとうございます

**Comment by moondoldo** [comment]
(Translate with translation software)
The issue has been resolved successfully, so I will close.
------------------------------
無事解決しましたので、Closeします
