### ISSUE TITLE
Add option to select ms store apps rather than directory

### ISSUE THREAD

**Issue by salmanuc** [ikas-mc/ContextMenuForWindows11#160]
I want to open pdf with xodo that is only available on ms store. The option is available in default context menu but within open with. I would rather have it in the right context main menu. Is there anyway to select ms store apps rather than pointing to directory as directory would change if the app is updated with newer version. 
Thank you.

**Comment by ikas-mc** [comment]
usually the store app will provide an app alias, (which can be found in Windows Settings-> Apps-> Advanched> Exection Aliases)
For example: emeditor , just use emeditor.exe xxx.txt

But this app does not provide it 
this app only provides the file suffix association

How is this menu configured? I didn't find a way to pass the path

**Comment by salmanuc** [comment]
in terminal this command opens the pdf
explorer xododocs://open?file=<file path>
how can i use it to create an entry in context menu?

**Comment by ikas-mc** [comment]
I installed the app ( https://www.microsoft.com/store/productId/9WZDNCRDJXP4 ), but it doesn't support this protocol ...
I can't test it 

try this:
exe: explorer.exe 
param: xododocs://open?file="{path}"

**Comment by salmanuc** [comment]
Thank you for your response, it appears that the command only works when xodo is set as default pdf viewer which counterintuitive
