### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by Y-PLONI** [ikas-mc/ContextMenuForWindows11#161]
Can you add support for right-to-left languages ​​[Hebrew, Arabic]?
Where can I upload a translation file?

**Comment by ikas-mc** [comment]
No need to upload, just import it in the settings

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/wiki/Languages

**Comment by Y-PLONI** [comment]
@ikas-mc 
I saw, I want the translation to be in the software, otherwise everyone will have to translate by themselves, isn't that a shame?

**Comment by ikas-mc** [comment]
You can upload it here,thanks for sharing

https://github.com/ikas-mc/ContextMenuForWindows11/discussions/categories/languages

next version, will add a link in the settings

**Comment by Y-PLONI** [comment]
@ikas-mc 
I uploaded!
Can you support RTL? In UWP apps it should be quite simple, although I don't know how to do it, I'm not a programmer...

**Comment by ikas-mc** [comment]
![Screenshot 2024-10-09 130706](https://github.com/user-attachments/assets/38e56528-3a8c-41cb-8522-2d31a0950652)
preview version

**Comment by Y-PLONI** [comment]
very beautiful!!!!
Thank you very much!!!
