### ISSUE TITLE
请问支持ARM设备么

### ISSUE THREAD

**Issue by Dazengx** [ikas-mc/ContextMenuForWindows11#162]
在我的arm设备上修改不了右键菜单，没有任何报错信息，但右键菜单就是没有任何改变。小米平板5，win11专业版22631.3447
谢谢！

**Comment by ikas-mc** [comment]
自动构建版本原生支持arm64

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/discussions/152

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.5.3.0
