### ISSUE TITLE
How to use with Specific Extension?

### ISSUE THREAD

**Issue by ghost1372** [ikas-mc/ContextMenuForWindows11#163]
I have used your library in my App, I know that it is easy to create any menu with your app, but because I am not using your app, I am only using your library.

Currently, i can see that my created menu in shown in Directory, Desktop, but it is not displayed on my extension which is PKG and PUP

```
<desktop4:Extension Category="windows.fileExplorerContextMenus">
		<desktop4:FileExplorerContextMenus>
				<desktop5:ItemType Type="Directory">
						<desktop5:Verb Id="CustomMenu" Clsid="ea2221a3-b449-4075-bff9-635769900e59"/>
				</desktop5:ItemType>
				<desktop5:ItemType Type=".PKG">
						<desktop5:Verb Id="CustomMenu" Clsid="ea2221a3-b449-4075-bff9-635769900e59"/>
				</desktop5:ItemType>
<desktop5:ItemType Type=".PUP">
						<desktop5:Verb Id="CustomMenu" Clsid="ea2221a3-b449-4075-bff9-635769900e59"/>
				</desktop5:ItemType>
				<desktop5:ItemType Type="Directory\Background">
						<desktop5:Verb Id="CustomMenu" Clsid="ea2221a3-b449-4075-bff9-635769900e59"/>
				</desktop5:ItemType>
		</desktop4:FileExplorerContextMenus>
</desktop4:Extension>
<uap3:Extension Category="windows.appExecutionAlias">
		<uap3:AppExecutionAlias>
				<desktop:ExecutionAlias Alias="PSXMaster.exe"/>
		</uap3:AppExecutionAlias>
</uap3:Extension>
```

if i change .PKG to *, my menu will be shown in all extensions.

```
ContextMenuItem menu = new ContextMenuItem
{
    Title = "Open PSXMaster Here",
    Param = @"""{path}""",
    AcceptFileFlag = (int)FileMatchFlagEnum.All,
    AcceptDirectoryFlag = (int)(DirectoryMatchFlagEnum.Directory | DirectoryMatchFlagEnum.Background | DirectoryMatchFlagEnum.Desktop),
    AcceptMultipleFilesFlag = (int)FilesMatchFlagEnum.Each,
    AcceptExts = ".pkg|.pup|.PKG|.PUP",
    Index = 0,
    Enabled = true,
    Icon = ProcessInfoHelper.GetFileVersionInfo().FileName,
    Exe = "PSXMaster.exe"
};
```

can you tell me how i can config for pkg and pup ext?

also i have some questions can you answer?
1. I have already set Alias (in Package.appxmanifest), do I have to set Exe part in creating the menu (ContextMenuItem.Exe)?
2. To define the extensions, do I have to define both the Package.appxmanifest and the ContextMenuItem.AcceptExts?
3. Is it case sensitive to define extensions? (PKG or pkg)
4. I have to use the exe file for the icon, can you also support the Relative paths? (Icon = "Assets/AppIcon.ico")

**Comment by ikas-mc** [comment]
The dll and the app are independent.
App:
Package.appxmanifest (<desktop4:Extension Category="windows.fileExplorerContextMenus">)
determines which files/folders will load menu dll

Package.appxmanifest (<uap3:Extension Category="windows.appExecutionAlias">)
Define an alias for invoking app from the command line

Menu Dll:
If dll is loaded, dll will check whether the file is supported or not according to the menu config(json)
if file is matched, menu will show in the context menu
If the menu is clicked, then it run the **EXE** ( menu config )

---

1. if dll used to run your app , menu config **EXE** must be your app Alias 
2. dll menu config  is a secondary filter. If you don't need to filter again, use only AcceptFileFlag = (int)FileMatchFlagEnum.All https://github.com/ikas-mc/ContextMenuForWindows11/blob/main/ContextMenuCustom/ContextMenuCustomHost/CustomSubExplorerCommand.cpp#L53
3. no,  tested, <desktop5:ItemType Type=".log"  > can match . LOG file
4. need to use absolute path

**Comment by ghost1372** [comment]
Thank you for your answer, i fixed my issue with changing Type to *****
```
<desktop5:ItemType Type="*">
		<desktop5:Verb Id="CustomMenu" Clsid="ea2221a3-b449-4075-bff9-635769900e59"/>
</desktop5:ItemType>
```

and  
```
AcceptFileFlag = (int)FileMatchFlagEnum.ExtList,
 AcceptExts = ".pkg|.pup",
```

i created a feature request issue for [Relative path](https://github.com/ikas-mc/ContextMenuForWindows11/issues/165), If it is not possible or for any other reason, be comfortable and close it.

**Comment by ikas-mc** [comment]
Didn't find a good way to implement it...
If your app is UWP, it is recommended to copy the icon to LocalData(first startup), then get the absolute address and set it to the  menu config

**Comment by ghost1372** [comment]
> Didn't find a good way to implement it...
> If your app is UWP, it is recommended to copy the icon to LocalData(first startup), then get the absolute address and set it to the  menu config
> 
> 

My app is winui, but i dont need to copy icon to localdata, i am geting exe file from ProcessInfo https://github.com/WinUICommunity/WinUICommunity/blob/main/dev/Core/Helpers/ProcessInfoHelper.cs
Tnx again
