### ISSUE TITLE
The menu cannot be scrolled!

### ISSUE THREAD

**Issue by Y-PLONI** [ikas-mc/ContextMenuForWindows11#166]
See screenshot.
![image](https://github.com/user-attachments/assets/b56c2b83-4be0-41c9-93fd-d055f1cc837d)
There is no scroll bar, the mouse doesn't let you scroll either.

**Comment by ikas-mc** [comment]
Preview release fixed
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.5.3.0
