### ISSUE TITLE
Subj is currently not available in your account

### ISSUE THREAD

**Issue by henrypp** [ikas-mc/ContextMenuForWindows11#184]
What is this????

i am on local account

![sshot-002](https://github.com/user-attachments/assets/36233e09-38ab-4004-9649-c9c3442d7f8a)

**Comment by maxwowpow** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/wiki/How-to-install
Release or Dev Packages -> Manual installation
Works for me.

**Comment by henrypp** [comment]
@maxwowpow maxwowpow

i dont know what im do wrong, i just reinstall windows and it happens, **all other uwp apps works fine**,

**Comment by ikas-mc** [comment]
first installation must be installed from the store

**Comment by henrypp** [comment]
before that, almost 4 years, there is no probmlems with local installation, i mean github package with certificate installation, of course, but in last 2 months in 24h2 something changed (idk what) and now requirements to install through ms store, complete do not know what changed, but it complete stupid as always same as win11 tray icon middle click [does not worked](https://github.com/ShareX/ShareX/issues/6846#issuecomment-2069082823)! *logiks problem*, lol

![image](https://github.com/user-attachments/assets/285d6dcf-dd82-4270-8587-f7e1b3ca05f0)
