### ISSUE TITLE
Is it possible to start a program as admin?

### ISSUE THREAD

**Issue by RichiK86** [ikas-mc/ContextMenuForWindows11#19]
Hello,
is it possible to start a program as admin?

**Comment by ikas-mc** [comment]
It is recommended to use a script to request the administrator, or to configure the target program compatibility, choose to use the administrator to execute

**Comment by RichiK86** [comment]
How can I use the script to request the administrator?

{
    "title":"open with  7zFM",
    "exe":"\"C:\\Program Files\\7-Zip\\7zFM.exe\"",
    "param":"\"{path}\"",
    "icon":"\"C:\\Program Files\\7-Zip\\7zFM.exe\",0",
    "acceptExts":".zip .7z .rar .exe .iso",
    "acceptDirectory":false
}

**Comment by ikas-mc** [comment]
@RichiK86  
Recommended to use this tool
https://github.com/gerardog/gsudo 

```
{
    "title":"open with  7zFM",
    "exe":"\"C:\\Program Files (x86)\\gsudo\\gsudo.exe\"",
    "param":"\"C:\\Program Files\\7-Zip\\7zFM.exe\" \"{path}\"",
    "icon":"\"C:\\Program Files\\7-Zip\\7zFM.exe\",0",
    "acceptExts":"*",
    "acceptDirectory":false
}
```
![120220112211758](https://user-images.githubusercontent.com/65895428/149147722-df50a0fc-568c-47f4-99e9-46d115804632.png)

**Comment by ALIENQuake** [comment]
@ikas-mc Hi,
starting with Windows 11, version 24H2, the build-in way would be to enable and use `sudo` as Exe. I've tested it and it works. May ask you to add an example to the Wiki?
