### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by ikas-mc** [ikas-mc/ContextMenuForWindows11#2]
# See Wiki

The page has been migrated to the wiki 

English:  
https://github.com/ikas-mc/ContextMenuForWindows11/wiki/Help

Chinese:  
https://github.com/ikas-mc/ContextMenuForWindows11/wiki/%E5%B8%AE%E5%8A%A9

=========================================================================

This app read the menu config files from the app's localdata folder, then create the context menu
The menu config use json format

## menu config sample
```
{
    "title":"open with  7zFM",
    "exe":"\"C:\\Program Files\\7-Zip\\7zFM.exe\"",
    "param":"\"{path}\"",
    "icon":"\"C:\\Program Files\\7-Zip\\7zFM.exe\",0",
    "acceptExts":".zip .7z .rar .exe .iso",
    "acceptDirectory":false
}
```

## config files folder
```
C:\Users\yourname\AppData\Local\Packages\{appId}\LocalState\custom_commands   
```
If you need to back up, just copy all the files here to a safe folder.

## manager ui
1. The left panel is used to add menus and view the menu list.the folder button is used to open config folder
2. The right panel is used to edit menu selected
3. click add and edit then save
![5](https://user-images.githubusercontent.com/65895428/138751496-d6e41cf7-8e5c-4d1f-b219-7a980ee47444.png)
As shown in the picture, it adds a menu: Open the file with Notepad

## variable 
```
 {path}  absolute address of the right-clicked file or folder
 {name}  file name (version>=1.1.2.0)
```

## more sample 
https://github.com/ikas-mc/ContextMenuForWindows11/tree/main/menuSample

## context menu
![Screenshot 2021-10-26 030516](https://user-images.githubusercontent.com/65895428/138754956-53b670ba-5cc3-4108-a129-1b3f9769c16a.png)

you can modify menu name in manager ui 

![Screenshot 2021-10-26 030914](https://user-images.githubusercontent.com/65895428/138755326-e1255309-2034-46b8-8ed3-e2d11b9449f1.png)

**Comment by ikas-mc** [comment]
## icon

### use icon from exe or dll

```
"C:\Program Files\7-Zip\7zFM.exe",0

C:\WINDOWS\System32\SHELL32.dll,196
```
note:
change a folder icon and open desktop.ini(hidden) in the folder to find the index number
https://support.microsoft.com/en-us/topic/cannot-change-the-default-folder-icons-in-windows-explorer-db49e15d-d95a-bc68-9947-e3ec296f4514
###  use icon file
```
"C:\Users\user\icons\icon.ico"
```

**Comment by ikas-mc** [comment]
## extension and folder match

### match extensions
```
# match extensions
.apk .apkx .mapk

# *  match all
*
```

### match  folder
check to match

![20211103162348](https://user-images.githubusercontent.com/65895428/140028429-735f7fc4-d16f-4e55-afaf-fabedbdef84b.png)

**Comment by moob158** [comment]
it is possible to show the menu without selecting a folder or file , like in version 1.1.2???

![Sem título](https://user-images.githubusercontent.com/60049180/140231028-b8a4a536-3dd5-484a-ae6a-6e521abb4f1b.png)

**Comment by FuurioBR** [comment]
{Path} is giving me "C:\Windows\System32\ + file name" instead of the "file path + file name" when running a batch from it.

**Comment by ikas-mc** [comment]
> {Path} is giving me "C:\Windows\System32\ + file name" instead of the "file path + file name" when running a batch from it.
[echo.zip](https://github.com/ikas-mc/ContextMenuForWindows11/files/7533155/echo.zip)

add this menu for a test...

**Comment by FuurioBR** [comment]
Ah, so I need \"{path}\", not only "{path}", it works now. Thanks.

**Comment by PeterleB** [comment]
{"title":"Bildvorschau","exe":"rundll32","param":"C:\\Program Files\\Windows Photo Viewer\\PhotoViewer.dll, ImageView_Fullscreen \\\"{path}\\\"","icon":"C:\\Program Files\\Windows Photo Viewer\\PhotoViewer.dll, 0","acceptExts":"\".jpg .jpeg .bmp .png .webp\"","acceptDirectory":false}

It doesn't work.
Can you help, please.

**Comment by ikas-mc** [comment]
@PeterleB
[Bildvorschau.zip](https://github.com/ikas-mc/ContextMenuForWindows11/files/7612937/Bildvorschau.zip)
 
\"{path}\"-> {path}

**Comment by PeterleB** [comment]
Thank you
