### ISSUE TITLE
link as path parameter

### ISSUE THREAD

**Issue by wf2020** [ikas-mc/ContextMenuForWindows11#20]
Hello,

first thank you for this app.

I found following problem: if the {path} parameter is a link it is used "as is" and not followed,

Example:
On the desktop I have a link to D:\ but instead resolving this path the parameter "C:\Users\Test\Desktop\Mylink.lnk" is passed.

**Comment by ikas-mc** [comment]
Thanks for the feedback
1. the "link" is indeed a real file, and the path is its address
2. The target exe may or may not resolve the address 

after test:
notepad3.exe = resolve the address 
vscode = not resolve the address

**Comment by wf2020** [comment]
If a *.lnk file is found, would it be possible to resolve the target path by your app?

**Comment by ikas-mc** [comment]
Yes, but I feel it is beyond the responsibility of this tool
