### ISSUE TITLE
可否把支持把旧版菜单中的选项也添加进来

### ISSUE THREAD

**Issue by Cielstar** [ikas-mc/ContextMenuForWindows11#22]
比如只使用7z打开压缩文件还是鸡肋了点，但如果把旧版菜单7z的右键菜单选项也可以添加到里面，可玩性就高了

**Comment by ikas-mc** [comment]
@Cielstar 
这个工具本身不提供任何菜单..你可以自己添加任何菜单....
7z那些最终也是调用了其自己的命令,只要找下写下配置就好了....

一直计划加入一个工具,可以读取系统旧版菜单,然后可以选择条目,然后自动转换到本应用

**Comment by Cielstar** [comment]
明白了
