### ISSUE TITLE
Environment Variables are not expanded

### ISSUE THREAD

**Issue by automate-this** [ikas-mc/ContextMenuForWindows11#23]
If you, for example, pass the following to powershell.exe
-File "%LocalAppdata%\Myscript.ps1" in Param, die %LocalAppData% does not get expanded.
Also it seems the %PATH% variable is not used. You have to hardcode the path to powershell.exe to get it working.

**Comment by ikas-mc** [comment]
[Exe] and [Param] does not parse environment variable values

But run [Exe] actually supports the programs in the PATH,so powershell do not need  the full path

Consider adding parsing support for environment variables in later versions
wil::ExpandEnvironmentStringsW<std::wstring>(raw)

**Comment by ayamadori** [comment]
As workaround, this should work well.

[Exe] `wt.exe` (You need Windows Terminal)
[Param] `powershell.exe -File "%LocalAppdata%\Myscript.ps1"`

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/3.0.0.0
