### ISSUE TITLE
[Feature request] Custom context menu entries outside of the "Open With" group

### ISSUE THREAD

**Issue by Ignis621** [ikas-mc/ContextMenuForWindows11#24]
As I said in the title, I'd love to see the custom context menu entries created with this app outside of the "Open With" group. Would it be possible to add that feature? Thanks!

**Comment by ikas-mc** [comment]
Windows 11 only allows apps to have one menu... 
Even multiple menus are created, they will automatically become multiple submenus

**Comment by Ignis621** [comment]
Well, that's unfortunate. However, thanks for responding and explaining it to me. Have a good one

**Comment by TimTrayler** [comment]
> Windows 11 only allows apps to have one menu... Even multiple menus are created, they will automatically become multiple submenus
Can't you add multiple entries and groups to the extended context menu (via registry)?
