### ISSUE TITLE
I can't use %ProgramFiles% or %SystemRoot% or any other environment variable in Exe field.

### ISSUE THREAD

**Issue by Smorvel** [ikas-mc/ContextMenuForWindows11#29]
![Screenshot 2022-04-03 183324](https://user-images.githubusercontent.com/19754243/161435603-e51837bf-db51-4ef9-abb4-14db7f780318.png)

**Comment by ikas-mc** [comment]
See
https://github.com/ikas-mc/ContextMenuForWindows11/issues/23
