### ISSUE TITLE
How to set correct order in my menu? (Move under or upper)

### ISSUE THREAD

**Issue by Smorvel** [ikas-mc/ContextMenuForWindows11#30]
![Screenshot 2022-04-03 183324](https://user-images.githubusercontent.com/19754243/161436038-5c4531ef-1dbe-4837-9c03-e7d7205a8eb7.png)

**Comment by Smorvel** [comment]
Also, menu is showing when I click on empty space (folder or desktop), would be nice if you disable it.

**Comment by ikas-mc** [comment]
Currently not supported, but can be resolved manually

Open the menu file folder
Add a numeric sequence to the file name
![20220404102351](https://user-images.githubusercontent.com/65895428/161463791-fe93f4a8-b20a-4aae-b6a1-1d9a53ec3e14.png)

If you use cache, then you need to refresh the cache

**Comment by ikas-mc** [comment]
> Also, menu is showing when I click on empty space (folder or desktop), would be nice if you disable it.

In the code, make the desktop as a folder,
https://github.com/ikas-mc/ContextMenuForWindows11/blob/5420edf1cc45a8fc92876a0e9ff813d271b8f577/ContextMenuCustom/ContextMenuCustomHost/CustomExplorerCommand.cpp#L92

So, it's the same as a normal folder.
This probably won't change
