### ISSUE TITLE
[Suggestion] icon color

### ISSUE THREAD

**Issue by KrazyLurt** [ikas-mc/ContextMenuForWindows11#31]
In light mode the outer rectangle on the context icon is white, it would be better to be light the rest of the win11 icons, i.e. rbg 126, 126, 126

Dark mode is perfect
![white](https://user-images.githubusercontent.com/75538575/161866337-e7171fc3-1701-431b-a15d-c6778b9a7523.png)

**Comment by ikas-mc** [comment]
Are you using a custom color theme?

Currently based on windows theme not app theme

**Comment by ikas-mc** [comment]
I found the problem...

The context menu is actually based on the app mode, which is inconsistent with the start menu and taskbar...
![20220406115755](https://user-images.githubusercontent.com/65895428/161892924-c7d7e413-9ba0-47f2-a5a8-774a0191dca7.png)



I will fix it in the next version...

https://github.com/ikas-mc/ContextMenuForWindows11/blob/5420edf1cc45a8fc92876a0e9ff813d271b8f577/ContextMenuCustom/ContextMenuCustomHost/CustomExplorerCommand.cpp#L42

SystemUsesLightTheme => AppsUseLightTheme

**Comment by KrazyLurt** [comment]
So with the future fix the white outer line will be more grey like windows 11 default icons as I marked in the scr above?

**Comment by ikas-mc** [comment]
yes.





![Screenshot 2022-04-06 121110](https://user-images.githubusercontent.com/65895428/161894145-47bc0f6c-dfa9-4a84-bcad-22ed47225d7c.png)

**Comment by KrazyLurt** [comment]
Look great, good work and thanks for the fast reply!

**Comment by ikas-mc** [comment]
@KrazyLurt 
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/2.5.0.0

**Comment by KrazyLurt** [comment]
Thanks, works perfect!
