### ISSUE TITLE
[Enhancement] Add hotkey Ctrl+S to save current item

### ISSUE THREAD

**Issue by RobbyMeeker** [ikas-mc/ContextMenuForWindows11#33]
Currently, it is slightly inconvenient to have to click the top-right save button each time you make a change.
Using a function to quickly save, using the keyboard shortcut Ctrl+S would make life a lot easier. I hope this will be considered for future versions.

**Comment by ikas-mc** [comment]
next version will add shortcuts to save, refresh, and delete

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/3.0.0.0

**Comment by RobbyMeeker** [comment]
> next version .. Add refresh, delete and save shortcut keys

Great change, thank you!
