### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by LucaSorvillo** [ikas-mc/ContextMenuForWindows11#38]
I created my entry but the menu does not change, so I tried with the templates present in menuSample but nothing has changed.
![gif1](https://user-images.githubusercontent.com/54334100/171012161-82fa6f48-6485-42dc-bfe0-22f346dcf532.gif)

Windows 11 Pro 22621.1

**Comment by Nekokan** [comment]
> Windows 11 Pro 22621.1

Samely, I use this app on Windows 11 Insider Preview (Beta) version.
It worked so nice before. but after updated 22621, this app doesn't work.
The menu is shown but no commands will be executed.

Is there something to solve? Or can I provide any information to solve?

**Comment by Catatomik** [comment]
Bump

**Comment by LucaSorvillo** [comment]
@Catatomik From what it seems the author of the repository is no longer active.
We can read from his profile:
"Sadly, for various reasons, I had to leave github for a while"

**Comment by Catatomik** [comment]
> @Catatomik From what it seems the author of the repository is no longer active. We can read from his profile: "Sadly, for various reasons, I had to leave github for a while"

Oh yes well seen.
Maybe someone will make a working fork of this nice app ?

**Comment by LucaSorvillo** [comment]
@Catatomik Wish it! I'm also very interested in this tool, on windows 10 I used to customize my context menus because it was so convenient. it's a pity I can't do it on the new context menu as well..

**Comment by LucaSorvillo** [comment]
@Catatomik News! I tried reinstalling it after windows updates and it seems to be working fine!
I installed it from here https://apps.microsoft.com/store/detail/custom-context-menu/9PC7BZZ28G0X
Probably the problem was the windows version.
Windows 11 Pro
22622.290

**Comment by Catatomik** [comment]
> @Catatomik News! I tried reinstalling it after windows updates and it seems to be working fine! I installed it from here https://apps.microsoft.com/store/detail/custom-context-menu/9PC7BZZ28G0X Probably the problem was the windows version. Windows 11 Pro 22622.290
> 
> Remember to able "Match Folder" and "Match file" if u need.

Really weird.
I already had it installed from the store, but reinstalling it from your link worked...

Perfect, thanks! I think you can close this.

**Comment by AgentFire** [comment]
Windows 11 Version 22H2 22621.963
Doesn't work at all.
