### ISSUE TITLE
可以设置成根据右击文件的后缀名显示不同的菜单吗

### ISSUE THREAD

**Issue by viewhang** [ikas-mc/ContextMenuForWindows11#4]
多个后缀名可以用分隔符分割，例如只有在右击apk文件时候才显示安装或者发送到wsa

**Comment by ikas-mc** [comment]
根据扩展显示,确实会更好..但是目前拿不到扩展名..等有时间了研究下

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/1.2.0.0
