### ISSUE TITLE
Feature Request: Add an entry directly in the right-click context menu and not in the "Open With" sub-menu

### ISSUE THREAD

**Issue by PrateekArya** [ikas-mc/ContextMenuForWindows11#45]
It may be a good idea to allow the user to directly add an entry to the right-click context menu instead of adding the new entry into the "Open With" (or whatever its renamed to) sub-menu.

**Comment by Garfounkel** [comment]
Agreed! Would love this feature as well.

**Comment by Alexis-BX** [comment]
This might be a stretch but the ability to create a tree structure, with both entries and sub-menus (like in regedit) would be amazing!

**Comment by UsainSrht** [comment]
I downloaded this app for this feature but it was sad to see there is not.

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/issues/24

Windows enforces that an app can only have one menu

**Comment by UsainSrht** [comment]
> #24
> 
> Windows enforces that an app can only have one menu

Is it possible to create fake apps to make this happen?

**Comment by SirHenryIII** [comment]
I know that PowerToys does have different entries for some modules. I don't know how much the method is different from yours but maybe worth a look.

**Comment by FlurinBruehwiler** [comment]
It would be nice, if only one menu is specified, then this menu appears on the "top level"

**Comment by ikas-mc** [comment]
@FlurinBruehwiler 

https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/3.5.0.0

**Comment by RieGo** [comment]
i agree, this would probably be the most wanted feature for many right now.
one bad workaround would probably be to create several helper applications and split the commands between them...
would love to see this happen

**Comment by Luk164** [comment]
> I know that PowerToys does have different entries for some modules. I don't know how much the method is different from yours but maybe worth a look.

Is this microsoft once again making proprietary workarounds? Like that time they made edge able to set itself as default browser automagically while all other browsers needed manual steps? (Until firefox reversed engineered it)

**Comment by huzhaoran2006** [comment]
> i agree, this would probably be the most wanted feature for many right now. one bad workaround would probably be to create several helper applications and split the commands between them... would love to see this happen
> 
> meanwhile... maybe we can make several msixbundle files and just change the identifier? this way we could have one app for one menu entry :) does anyone know, what we have to change, to make it possible to install in parallel?

i think it works

**Comment by ge9** [comment]
> i agree, this would probably be the most wanted feature for many right now. one bad workaround would probably be to create several helper applications and split the commands between them... would love to see this happen
> 
> meanwhile... maybe we can make several msixbundle files and just change the identifier? this way we could have one app for one menu entry :) does anyone know, what we have to change, to make it possible to install in parallel?

I also hope this (create "clone" apps with different identifiers).

**Comment by e-t-l** [comment]
> I know that PowerToys does have different entries for some modules. I don't know how much the method is different from yours but maybe worth a look.

That's because each PowerToys utility is a separate executable.

**Comment by amirrezaDev1378** [comment]
+1

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/wiki/Create-Custom-Package

**Comment by 03302024** [comment]
> https://github.com/ikas-mc/ContextMenuForWindows11/wiki/Create-Custom-Package

I wish there was an easier way to achieve this. Not everybody is knowledgeable enough to go through those steps.
