### ISSUE TITLE
Right click doesn't trigger on compiled version

### ISSUE THREAD

**Issue by shooddelta** [ikas-mc/ContextMenuForWindows11#47]
I installed the Windows Store Version and the application works greats.

I downloaded the sources code, and made the packaged did a sideload installed.  When i add my menu item, the action is not trigger when I click on it.  Am I missing something?

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/blob/main/build.md

Actually, this is how I do it myself....

**Comment by huzhaoran2006** [comment]
> https://github.com/ikas-mc/ContextMenuForWindows11/blob/main/build.md
> 
> 实际上，我自己就是这样做的。

Can you share your packaged version with me? I tried to package but failed

**Comment by ikas-mc** [comment]
see actions
