### ISSUE TITLE
Parameter in exe path not possible?

### ISSUE THREAD

**Issue by Cris--** [ikas-mc/ContextMenuForWindows11#48]
Hi,

if i add `"C:\Program Files (x86)\EasyJoin\easyjoin.exe" --sendto-3s49pgld3mkc41cl14u6ghev03` to Exe field it didn't work.
Did i something wrong?

**Comment by ikas-mc** [comment]
use [param]

[param] :  --sendto-3s49pgld3mkc41cl14u6ghev03
