### ISSUE TITLE
Support for Windows 11 22H2 (build 22621)

### ISSUE THREAD

**Issue by DaBear78** [ikas-mc/ContextMenuForWindows11#49]
In Windows 11 22H2 (build 22621) the custom menu is not showing until I open the main tool once. For the rest of the session the menu appears, but is gone once again after a restart.

**Comment by bycore** [comment]
I was in "Windows 11 Insider Preview Build 22622.575". After setting the software, restart your computer.
![image](https://user-images.githubusercontent.com/40348220/184468542-ac245312-f647-4f2c-8538-4e96c4a90f57.png)

**Comment by DaBear78** [comment]
Restarted my computer a few times (with and without opening the tool before), nothing worked. I uninstalled the software and installed it again (backuped the settings before), restored my settings and now it works. Thx.
