### ISSUE TITLE
Refresh Menus Folder

### ISSUE THREAD

**Issue by lastpust** [ikas-mc/ContextMenuForWindows11#5]
I think it should be "Open Menus Folder" Instead of "Refresh"

also may i ask for a feature can u add support for editing "Create New" menu? because right now
.txt and .bmp cannot be removed from new and old context menu
also .ps1 cannot be added

**Comment by lastpust** [comment]
Also can u make it portable and let us export and import without a interface, via cmd or powershell would be great. so that we can use it in setupcomplete maybe?

**Comment by lastpust** [comment]
Also can we hide the custom menu when right clicked to desktop? or maybe can we add extension support? for exp open with notepad only available with selected extensions as txt bat cmd reg vbs ps1 etc

open with notepad on desktop is meaningless and gives error

**Comment by ikas-mc** [comment]
it is "Open Menus Folder", I will modify it next version 
This app uses standard api , cannot  modify the "new" menu
It is built using uwp, so it is difficult ... may be replaced by windows app sdk in the future 
It is indeed a better way to display based on the extension.. But now the api is limited... 
Those menus are just some examples...

**Comment by lastpust** [comment]
ok thanks for quick fix and answer, i will be following your tools every day. thanks!

**Comment by ikas-mc** [comment]
😂 😂 
may not update frequently, I don't have much free time

**Comment by CrypticCus** [comment]
+1 to these requests they would be awesome, win11 needs this project desperately and since you started it i hope u keep it going for a bit more.

**Comment by CrypticCus** [comment]
I would ask for multiple menu or only item support 
also setting for no icon

**Comment by ikas-mc** [comment]
> I would ask for multiple menu or only item support also setting for no icon
icon
https://github.com/ikas-mc/ContextMenuForWindows11/issues/2#issuecomment-956425338

**Comment by CrypticCus** [comment]
i mean no icon i an place icons thank you

**Comment by ikas-mc** [comment]
add file match
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/1.2.0.0

**Comment by CrypticCus** [comment]
yes it works great
match extension is perfect

but also need match file because when you match folder they also work on all files...
or need match extension NONE so it works only for folders

**Comment by moob158** [comment]
it is possible to show the menu without selecting a folder or file , like in version 1.1.2???

![Sem título](https://user-images.githubusercontent.com/60049180/140231028-b8a4a536-3dd5-484a-ae6a-6e521abb4f1b.png)

**Comment by CrypticCus** [comment]
use "*" for everything
use "" for nothing

its already inside software shown as example. but you shouldn't show everything for everything. it won't be correct approach. if it was windows would have done it years ago... every extension for every software.

**Comment by moob158** [comment]
Not work in version 1.2

In version 1.2 the context menu only show if select an folder or file

I use this to open programs not files or folders

**Comment by CrypticCus** [comment]
as i said,
use "*" for everything
use "" for nothing

it is working for 1.2. tested verified.

**Comment by moob158** [comment]
Not work here

![1](https://user-images.githubusercontent.com/60049180/140406888-e8976587-2171-4af2-aba9-0167de8a5e09.gif)

**Comment by CrypticCus** [comment]
you did not say anything about desktop you just said i use it to open programs.. and you can open anything by clicking on file or a folder but it doesn't work on desktop anymore. maybe he can add a switch for that too.

use "desktop" word next time.

**Comment by ikas-mc** [comment]
@moob158  @CrypticCus 
may be a bug
the dev version win11 does not display any third-party context menus when right clieck no file. so I may miss this bug
I will test and fix later

**Comment by ikas-mc** [comment]
@CrypticCus 
the new menu need to wait..
https://github.com/BluePointLilac/ContextMenuManager/issues/97
i use ContextMenuManager to modify menu in windows 10 before

**Comment by ikas-mc** [comment]
update to 1.2.14.0

**Comment by moob158** [comment]
@ikas-mc 

thank you, I will test :)

**Comment by CrypticCus** [comment]
thanks for contextmenumanager advice but its not supporting windows 11 there are no one supporting win11 but you
