### ISSUE TITLE
Help with translate (suggestion)

### ISSUE THREAD

**Issue by Marksonthehost** [ikas-mc/ContextMenuForWindows11#50]
I have a Chinese friend who is not good at computers, but he wants to make his Windows easier to use, so he asks me if there is a way to add programs to the Windows 11 new context menu
I recommended this tool to him, and then he said he didn't understand English and asked me to translate😂 (i'm a programmer and he thinks programmers can do anything lol)
So you know👍

**Comment by ikas-mc** [comment]
see chinese wiki
https://github.com/ikas-mc/ContextMenuForWindows11/wiki/%E5%B8%AE%E5%8A%A9

More languages will be added later
