### ISSUE TITLE
Can you add the ability to delete options that come with Windows?

### ISSUE THREAD

**Issue by Inkshow** [ikas-mc/ContextMenuForWindows11#51]
Like this
![image](https://user-images.githubusercontent.com/79002121/185770264-94ca4419-31e7-445c-8dbd-162ce69ea7f1.png)

**Comment by ikas-mc** [comment]
no

This app just uses the api provided by windows

**Comment by Inkshow** [comment]
> no
> 
> This app just uses the api provided by windows

All right
