### ISSUE TITLE
Can't install through Powershell

### ISSUE THREAD

**Issue by ararezaee** [ikas-mc/ContextMenuForWindows11#52]
I downloaded the msixbundle file from github and installed it with all its dependencies like UI XAML.
But it doesn't open the app for me, gives this error instead: "There’s a problem with Custom Context Menu. Reinstall the application from its original install location or contact your administrator."

**Comment by ikas-mc** [comment]
msixbundle here is just a backup of the store..
It is recommended to go directly to the store for installation
