### ISSUE TITLE
add new variable

### ISSUE THREAD

**Issue by Inkshow** [ikas-mc/ContextMenuForWindows11#53]
If I want to decompress the file with 7zip, the folder will have the extension name and ~
It's not pretty, thanks.

**Comment by ikas-mc** [comment]
will add later

**Comment by Inkshow** [comment]
> will add later

👍

**Comment by SsparKluo** [comment]
> will add later

Sorry to bother, but is the {name} the new var to get filename without extension name?

**Comment by Inkshow** [comment]
> > will add later
> 
> Sorry to bother, but is the {name} the new var to get filename without extension name?

I'm sorry to say that I solved it long ago.
It's the Chinese documentation that doesn't mention it.
I'm very sorry for taking your time.

**Comment by Inkshow** [comment]
> > will add later
> 
> Sorry to bother, but is the {name} the new var to get filename without extension name?

I'm sorry to say that I solved it long ago.
It's the Chinese documentation that doesn't mention it.
I'm very sorry for taking your time.
