### ISSUE TITLE
Self signed app concern "Add-AppxPackage: Cannot find path"

### ISSUE THREAD

**Issue by FadeMind** [ikas-mc/ContextMenuForWindows11#56]
HI @ikas-mc 

I followed your guide in self signed with new cert package
During operations I have got error:
```
Add-AppxPackage: Cannot find path 'D:\fademind\Desktop\ccs\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx D:\fademind\Desktop\ccs\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx D:\fademind\Desktop\ccs\Dependencies\x64\Microsoft.UI.Xaml.2.6.appx D:\fademind\Desktop\ccs\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx' because it does not exist.
```
I restored `Set-ExecutionPolicy` to default and just opened FILE `ContextMenuCustomPackage_3.1.0.0_x64.msixbundle` 
Now install went fine.

**Comment by ikas-mc** [comment]
unzip it, the Dependencies\x64 files all exist......so strange
Once the certificate is imported, and the dependencies have been installed.. u can Just install it directly

**Comment by Sansui233** [comment]
The same problem with Powershell 7. It seems that the string of four deps is regarded as one path with spaces. Powershell 5 works.
