### ISSUE TITLE
Access from WinUI 3

### ISSUE THREAD

**Issue by ghost1372** [ikas-mc/ContextMenuForWindows11#57]
Hi, Can you create a Library with easy access in C# (WinUI 3)?

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/tree/main/ContextMenuCustom/ContextMenuCustomHost
This is an independent project...
Can be used in winui3


```
<com:Extension Category="windows.comServer">
          <com:ComServer>
            <com:SurrogateServer  DisplayName="Custome Context Menu">
              <com:Class Id="46F650E5-9959-48D6-AC13-A9637C5B3787" Path="ContextMenuCustomHost.dll" ThreadingModel="STA"/>
            </com:SurrogateServer>
 </com:ComServer>

```

**Comment by ghost1372** [comment]
@ikas-mc  tnx, i used in my app and i cant see my menu!
![image](https://user-images.githubusercontent.com/9213496/187028904-303652f5-e991-4b29-af86-541e06e2cfdb.png)
Should I do something else?

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/blob/main/ContextMenuCustom/ContextMenuCustomPackage/Package.appxmanifest

**Comment by ghost1372** [comment]
I still can't see the created menu.
Do I have to change something special in vcxproj? or something else in appxmanifest?
I copied your codes exactly
[App31.zip](https://github.com/ikas-mc/ContextMenuForWindows11/files/9439600/App31.zip)

**Comment by ghost1372** [comment]
@ikas-mc  I'm still having trouble creating a menu, Can you take a look at what I'm doing?
i added **ContextMenuCustomHost** project to my project and i added as a refrence project. then I specified the output location of the project
![image](https://user-images.githubusercontent.com/9213496/205477962-1a3cf452-febe-4e22-8c53-b6a2527ce63a.png)

I also edited the manifest file

```
<Extensions>
        <desktop4:Extension Category="windows.fileExplorerContextMenus">
          <desktop4:FileExplorerContextMenus>
            <desktop5:ItemType Type="Directory"  >
              <desktop5:Verb Id="CustomMenu" Clsid="46F650E5-9959-48D6-AC13-A9637C5B3787" />
            </desktop5:ItemType>
            <desktop5:ItemType Type="*"  >
              <desktop5:Verb Id="CustomMenu" Clsid="46F650E5-9959-48D6-AC13-A9637C5B3787" />
            </desktop5:ItemType>
            <desktop5:ItemType Type="Directory\Background">
              <desktop5:Verb Id="CustomMenu" Clsid="46F650E5-9959-48D6-AC13-A9637C5B3787" />
            </desktop5:ItemType>
          </desktop4:FileExplorerContextMenus>
        </desktop4:Extension>
        <com:Extension Category="windows.comServer">
          <com:ComServer>
            <com:SurrogateServer  DisplayName="Custome Context Menu">
              <com:Class Id="46F650E5-9959-48D6-AC13-A9637C5B3787" Path="ContextMenuCustomHost.dll" ThreadingModel="STA"/>
            </com:SurrogateServer>
          </com:ComServer>
        </com:Extension>
		  <uap3:Extension Category="windows.appExecutionAlias">
			  <uap3:AppExecutionAlias>
				  <desktop:ExecutionAlias Alias="customeContextMenuDebug.exe"/>
			  </uap3:AppExecutionAlias>
		  </uap3:Extension>
      </Extensions>
```

I ran the app, but I didn't see any new menu for my program, I restarted the Explorer, I still didn't see anything.
I decided to create a menu (json):

```
private async void myButton_Click(object sender, RoutedEventArgs e)
        {
            MenuService menuService = new MenuService();
            var menu = new MenuItem
            {
                Exe = "\"C:\\Program Files\\Notepad3\\Notepad3.exe\"",
                Param = "\"{path}\"",
                Title = "open in notepad"
            };
            await menuService.SaveAsync(menu);
        }
```
Nothing happens again.
Where is my work wrong, what have I left out?

**Comment by ikas-mc** [comment]
[ContextMenuCustom-winui3.zip](https://github.com/ikas-mc/ContextMenuForWindows11/files/10187719/ContextMenuCustom-winui3.zip)

![1](https://user-images.githubusercontent.com/65895428/206518233-143998e5-60f5-472e-aed6-e68d8ea14993.png)


0. backup some menu json 
1. uninstall ContextMenuCustomApp(uwp)
2.build host, copy to ContextMenuCustom-winui3, run ContextMenuCustom-winui3,then ,click button to open config folder
3.copy menu json to folder

**Comment by ghost1372** [comment]
> @ghost1372 
> 
> [ContextMenuCustom-winui3.zip](https://github.com/ikas-mc/ContextMenuForWindows11/files/10187719/ContextMenuCustom-winui3.zip)
> 
> ![1](https://user-images.githubusercontent.com/65895428/206518233-143998e5-60f5-472e-aed6-e68d8ea14993.png)
> 
> 
> 1. backup some menu json 
> 2. uninstall ContextMenuCustomApp(uwp)
> 3. build host, copy dll to ContextMenuCustom-winui3, run ContextMenuCustom-winui(package),then ,click button to open config folder
> 4. copy menu json to folder
> 

Thanks, I learned how to use it completely

**Comment by ghost1372** [comment]
Hi @ikas-mc 
I have a question, I want to run my packaged app when the menu is clicked, so what should I enter in the **exe** section?  As you know, the exe file of the packaged programs does not run

**Comment by ghost1372** [comment]
i added **windows.appExecutionAlias** But I don't know how to create a menu?
I am doing this now:
```
<uap3:Extension Category="windows.appExecutionAlias">
<uap3:AppExecutionAlias>
	<desktop:ExecutionAlias Alias="customeContextMenuDebug.exe"/>
</uap3:AppExecutionAlias>
</uap3:Extension>
```
and menu:
`{
"title":"Open Custom App Menu Here",
"exe":"C:\\Users\\mahdi\\source\\repos\\App5\\App5\\bin\\x86\\Debug\\net6.0-windows10.0.19041.0\\win10-x86\\App5.exe",
"param":"{path}",
"icon":"",
"acceptExts":"",
"acceptDirectory":true,
"acceptMultipleFiles":false,
"acceptMultipleFilesFlag":0,
"pathDelimiter":"",
"paramForMultipleFiles":""
}`

Nothing happens when I click on the menu
