### ISSUE TITLE
Can it create a custom context menu on Windows 10?

### ISSUE THREAD

**Issue by ElitePheonix2009** [ikas-mc/ContextMenuForWindows11#59]
I am using Windows 10, and I would like to create a custom context menu. Can it work on Windows 10?

**Comment by Luk164** [comment]
I am pretty sure this is meant for win11 only as it leverages the new way to make custom menus. For win10 there are alternatives like https://github.com/oleg-shilo/shell-x

**Comment by ElitePheonix2009** [comment]
Thanks
