### ISSUE TITLE
[Proposal] Handle multiple files/folders

### ISSUE THREAD

**Issue by ayamadori** [ikas-mc/ContextMenuForWindows11#6]
It seems to handle only one file now even if multiple files is selected.
Is this proposal technically possible?
I want to use as the alternative of `SendTo` folder.

**Comment by ikas-mc** [comment]
api supports multiple files
current difficulty is to find a convenient way to pass parameters

**Comment by ayamadori** [comment]
If only there is an option that replace `{path}` to absolute address of all selected files, it's helpful for me.

**Comment by ikas-mc** [comment]
Maybe app can send the addresses (separated by ;) to script, and then the custom script handles all by itself

**Comment by ayamadori** [comment]
I think that ` ` (=halfwidth space) (and `"`) is better than `;` for separator because it's more popular.
For example, drag & drop to multiple files to Windows Terminal is shown below.
![image](https://user-images.githubusercontent.com/7036267/141115951-230981be-32fe-40fe-a59b-5b2a13338259.png)
![image](https://user-images.githubusercontent.com/7036267/141116048-c5993c13-9bff-44f4-8895-0d4c58ecba61.png)

**Comment by ikas-mc** [comment]
I have create a branch for dev and test, but there are still problems...
the script needs to split the address, and the " " is difficult to make clear 
may can only choose "|", script parsing is also necessary

**Comment by rubenalamina** [comment]
I'm looking forward for it to pass multiple files. I use it for programs like hash verifiers, audio/image taggers (tagscanner, exiftool, etc) and others. So far this is a great utility. If you need someone to check or test let me know, I'm more than willing to lend a hand in testing or verifying your implementation of this.

**Comment by rxboy1983** [comment]
Is possible to add option to remove item "Compress to ZIP file"?
I cleaned up the context menu and removed a lot of options by editing the shell32.dll.mui and editing the registry. Only the option "Compress to ZIP file" I do not know how to remove.

**Comment by ikas-mc** [comment]
> Is possible to add option to remove item "Compress to ZIP file"? I cleaned up the context menu and removed a lot of items by editing the shell32.dll.mui and editing the registry. Only item "Compress to ZIP file" I do not know how to remove. I don't need this item because I use WinRAR for archiving.

This is difficult, this software uses standard APIs, and there is no way to do it...

**Comment by rubenalamina** [comment]
> This is difficult, this software uses standard APIs, and there is no way to do it...

I think this is out of the scope of your program (at least for now at the least) since it's not meant to customize windows own context menu entries but to create its own entry with whatever commands we want in the submenu.

BTW, any progress on the handling of multiples files/folders?

**Comment by ikas-mc** [comment]
There are a lot of problems to consider after the test of the branch created before..
temporarily shelved

**Comment by kirides** [comment]
In old context menu, selecting multiple files resulted in calling the .bat N-times

1. Rightclick with many files selected
2. Select some option configured using regedit
3. See that the selected option (e.g. Batch script) is opened N times, each invokation with one of the selected paths

i frequently used that behavior to transcode audio and video files using a bunch of ffmpeg based Batch scripts and the aforementioned behavior

**Comment by ikas-mc** [comment]
Add an option to call the "exe" for each address

**Comment by ayamadori** [comment]
Maybe off-topic, this seems to be very difficult... :(
https://stackoverflow.com/questions/6714165/powershell-stripping-double-quotes-from-command-line-arguments

**Comment by ikas-mc** [comment]
![1](https://user-images.githubusercontent.com/65895428/152789148-fc5bc8c2-4ab5-45b3-9645-d2c9c520b4dc.png)


Added multiple files support..
Depends on the target program to parse.0..
Difficult to use...

**Comment by kirides** [comment]
Without checking the implementation, does it "quote" the paths?
Without quoting it's more or less "useless".
There shouldn't be a need to "escape" the file path, just quoting would suffice (unless you put the input into a shell interpreter like CMD or smth like that, but that's another problem)

almost all applications support input like `my.exe "this is a string"` and correctly parse the input as a single, char* instead of `char[4]{` `"this`, `is`, `a`, `string"` `}`

So there would at least need to be an "option" to quote the input before sending it as args

**Comment by ikas-mc** [comment]
@kirides 
see wiki
"quote" every path as default 

I'll upload the code later and release a dev package

**Comment by ayamadori** [comment]
@ikas-mc 
I tested on 1.9.0.0_test.
In my case, this works well when the delimiter is ` ` (space)!

**Comment by kirides** [comment]
finally came around to test the 1.9.0.0 test build

Works great!

While i did have to modify my scripts slightly for it to work it does a great job.
(it passes multiple parameters now instead of invoking for each parameter like in the old fashioned context menu)

here is an example of a batch file that remuxes anything to a mkv

```bat
@ECHO OFF

for %%i in (%*) do (
    pushd %%~dpi
	
    "mkvmerge.exe" -o "remuxed-%%~ni.mkv" ="%%~nxi"
)
```

and here is the configuration used
![image](https://user-images.githubusercontent.com/13602143/154837765-f0b2af86-7a3e-4136-beb1-4d272b00f466.png)

**Comment by ikas-mc** [comment]
@kirides 
thanks for test

Based on the previous discussion, using a script  is sometimes really necessary

but
invoke [exe] for each paths,I will add an option when I have time

**Comment by ikas-mc** [comment]
Refactored multiple files support implementation
**each mode** 
![1](https://user-images.githubusercontent.com/65895428/155985015-1bef0071-20f7-4e41-9326-8489d3683969.png)

**join mode,same as v1.9** 
![2](https://user-images.githubusercontent.com/65895428/155985025-77ccff31-c503-4958-93a8-26fcfbe154e2.png)
