### ISSUE TITLE
能否添加到一级菜单，就像「在终端打开」

### ISSUE THREAD

**Issue by liplushe** [ikas-mc/ContextMenuForWindows11#60]
![Snipaste_2022-11-05_22-10-41](https://user-images.githubusercontent.com/52035356/200124085-e79f16fb-c395-4185-9fd2-31fde4969c11.png)
能不能实现这样的效果呢

**Comment by Luk164** [comment]
I would like to help but I have no idea what you need, mind using english please? I would rather not rely on a translator.

**Comment by liplushe** [comment]
> I would like to help but I have no idea what you need, mind using english please? I would rather not rely on a translator.

Can it be added to the first-level menu, like "Open in terminal"

**Comment by Luk164** [comment]
> 

Unfortunately, no. Windows seems to enforce only one menu entry per application to prevent clutter. This has already been answered in a different issue. If you really need it, you can switch to the old context menu and use one of the older utilities to achieve what you want.

**Comment by liplushe** [comment]
Thank you for response
