### ISSUE TITLE
Context Menu not added for Office?

### ISSUE THREAD

**Issue by Rex501st** [ikas-mc/ContextMenuForWindows11#61]
I want to add a menu to quickly create office files; I don't have the option from the actual office apps for some reason; so I am trying to recreate it with this app. This is what I have, but it doesn't work. Any help is appreciated. 

![image](https://user-images.githubusercontent.com/25782090/200339970-d9a6f41a-b71b-4440-92c4-21ac92e4508f.png)

**Comment by ikas-mc** [comment]
sorry,i do not use ms office
find the right script to create office files, then add as menu
