### ISSUE TITLE
 [Future] Run the program with specified parameters

### ISSUE THREAD

**Issue by RCUTANF** [ikas-mc/ContextMenuForWindows11#62]
As the title said, Could this program supports this?
![image](https://user-images.githubusercontent.com/110910565/208271186-113b149b-d2b7-4304-89d2-0f24f07960e6.png)
Just add a Input Box below.For example: 
EXE: cmd.exe
specified parameters: shutdown -h

**Comment by ikas-mc** [comment]
exe :shutdown.exe 
param : -h
