### ISSUE TITLE
传输文件/图片到wsa的Download的脚本

### ISSUE THREAD

**Issue by ZhengWugeng** [ikas-mc/ContextMenuForWindows11#64]
adb connect 127.0.0.1:58526
start cmd /k "adb -s 127.0.0.1:58526 push -p "%~1" /sdcard/Download/"%~n1%~x1" && adb -s 127.0.0.1:58526 shell  am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE -d file:///sdcard/Download && timeout /t 1 && exit"

这两行命令可以用于传输文件或者图片到wsa，并且刷新媒体库以防wsa的应用显示不出来新添加的文件。
把这两行写在bat文件里，然后在Custom Context Menu里面，EXE填bat文件路径，Param填"{path}"即可

**Comment by huzhaoran2006** [comment]
谢谢

**Comment by wordscode** [comment]
大佬
adb -s 127.0.0.1:58526 push -p "%~1" /sdcard/Download/"%~n1%~x1"
这个命令改成cmd命令是可行的吗？我看了adb push  没有%~1这些参数，这是属于bat文件的

**Comment by ZhengWugeng** [comment]
> 大佬 adb -s 127.0.0.1:58526 push -p "%~1" /sdcard/Download/"%~n1%~x1" 这个命令改成cmd命令是可行的吗？我看了adb push 没有%~1这些参数，这是属于bat文件的

我不太清楚，你可以搜一下cmd命令行里面有没有类似的语句。

**Comment by userzzzq** [comment]
> 大佬 adb -s 127.0.0.1:58526 push -p "%~1" /sdcard/Download/"%~n1%~x1" 这个命令改成cmd命令是可行的吗？我看了adb push 没有%~1这些参数，这是属于bat文件的

%~1这个属于CLI技巧，代表「输入文件」，任何CLI程序都可以用

**Comment by anthem216** [comment]
已经配置了adb环境变量，系统为Windows11，设置成功了，但是无法传从PC到WSA中去，安卓子系统的版本为2303.40000.5.0

**Comment by anthem216** [comment]
成功了，把.bat文件放在C盘，在没有中文路径的情况下下，终于实现了文件从PC传过WSA去
