### ISSUE TITLE
提供多个不同签名的包

### ISSUE THREAD

**Issue by huzhaoran2006** [ikas-mc/ContextMenuForWindows11#66]
如果在系统中注册成为多个应用
是不是就可以显示在一级菜单里
是否能在应用程序里提供 生成一个签名不同的appx安装包 的功能

**Comment by ikas-mc** [comment]
即使不同的包也是不行的...
需要修改源码 

https://github.com/ikas-mc/ContextMenuForWindows11/blob/4b6a76d87d77956d2a3580ceedf9dd3335b5e6af/ContextMenuCustom/ContextMenuCustomHost/CustomExplorerCommand.h#LL6C6-L6C6

https://github.com/ikas-mc/ContextMenuForWindows11/blob/4b6a76d87d77956d2a3580ceedf9dd3335b5e6af/ContextMenuCustom/ContextMenuCustomPackage/Package.appxmanifest#L64




关注以上  46F650E5-9959-48D6-AC13-A9637C5B3787

**Comment by huzhaoran2006** [comment]
> 

不好意思  我不太懂编程  请问是只要修改uuid后打包就可以了吗？
