### ISSUE TITLE
Multiple submenu entries appear but are not working

### ISSUE THREAD

**Issue by Aronjlove** [ikas-mc/ContextMenuForWindows11#67]
Like the title says, if I make multiple submenu entries, the submenus appear but clicking on either does not work.
![image](https://user-images.githubusercontent.com/42818757/211126656-17bf1156-dafa-4df1-bed0-0cd98619244c.png)

If I delete either of the submenus so only the top-level entry appears, then clicking on it will work
![image](https://user-images.githubusercontent.com/42818757/211126690-9f4de899-1b53-4580-92dc-0f717f08a50b.png)

This was working previously.  I had Everything Search and Notepad++ entries under the Custom menu, and clicking on either would bring up the application.

I uninstalled the Windows Store version and reinstalled it, and I had the same experience.

Is there anything I can try differently?

**Comment by ikas-mc** [comment]
can you upload your  json files here..

**Comment by Aronjlove** [comment]
[Everything 1.5a.json.txt](https://github.com/ikas-mc/ContextMenuForWindows11/files/10461920/Everything.1.5a.json.txt)
[Notepad++.json.txt](https://github.com/ikas-mc/ContextMenuForWindows11/files/10461921/Notepad%2B%2B.json.txt)
Here you go. Thanks.

**Comment by znwuyi** [comment]
the same problom, it can work well in desktop but do not work in explorer

**Comment by ikas-mc** [comment]
For a long time, I couldn't reproduce this issue on different computers
I also had this issue with my computer after an update
the latest version, I tried to fix this bug
