### ISSUE TITLE
Provide multiple installation packages with different signatures

### ISSUE THREAD

**Issue by huzhaoran2006** [ikas-mc/ContextMenuForWindows11#68]
It is found that the old and new versions can coexist, but only one is displayed
If change all the relevant information, can it display two menus in windows?

**Comment by RieGo** [comment]
I just tried installing microsoft store version and github version, but they somehow seem to conflict.
They don't share the same settings, but i can't see context menu of one installation...
so there is probably more to change.
I really hope the dev can find a way to install as many instances as we like. would definitely donate for that.

**Comment by huzhaoran2006** [comment]
> 我刚刚尝试安装微软商店版本和github版本，但它们似乎以某种方式冲突。它们不共享相同的设置，但我看不到一个安装的上下文菜单......所以可能还有更多需要改变的地方。我真的希望开发人员能找到一种方法来安装任意数量的实例。肯定会为此捐款。

So do I

**Comment by ikas-mc** [comment]
Need to modify the source code, change the **com uuid**

**Comment by huzhaoran2006** [comment]
> 需要修改源码，更改**通信uuid**

I  installed VS but failed to build. What components do I need to install for packaging to succeed？  （It shows that the SDK cannot be found, but I have installed it）

or If it is convenient for you, could you provide it in the release by the way

@ikas-mc

**Comment by huzhaoran2006** [comment]
> 

我更改了所有的这个uuid  
并且安装后有了两个应用 
可他们仍然共享菜单

![image](https://user-images.githubusercontent.com/104875469/213612693-e7a8fcc9-577c-421a-8308-766ec0496145.png)

**Comment by huzhaoran2006** [comment]
谢谢 成功了！！！
