### ISSUE TITLE
Impossible to leave arguments empy

### ISSUE THREAD

**Issue by sgachoud** [ikas-mc/ContextMenuForWindows11#69]
I am trying to create an entry for msys but it is impossible to leave the argument field empty, which is required for msys. Changing the .json of the entry and setting an empty string works.

**Comment by ikas-mc** [comment]
thanks 
will  remove [param] check  next version

**Comment by sgachoud** [comment]
Thanks!

**Comment by ikas-mc** [comment]
3.8.0.0 remove param check
