### ISSUE TITLE
Extensions are case sensitive

### ISSUE THREAD

**Issue by CrypticCus** [ikas-mc/ContextMenuForWindows11#7]
![1](https://user-images.githubusercontent.com/93516630/140885600-da385d17-ff0d-436c-93cc-ddccac1d3828.png)
if i type .iso it won't work.
if i type .ISO it does work.

**Comment by ikas-mc** [comment]
I forgot to ignore the case ,  will be fixed later

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/1.3.1.0

**Comment by CrypticCus** [comment]
> https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/1.3.1.0

now there is problem about matchfolder, i don't check it but everything can be accesible when right clicked to folder.

![image](https://user-images.githubusercontent.com/93516630/141185891-6ac80456-9a1d-47c1-ac3e-32ae67671ee0.png)
but as u can see match folder is not checked
![image](https://user-images.githubusercontent.com/93516630/141185933-632d4110-bc90-4617-a5ae-4e9d0a8ae68e.png)

**Comment by ikas-mc** [comment]
Thanks for your test 
but.i tested on 2 computers...the problem cannot be reproduced...

**Comment by CrypticCus** [comment]
hi insist on it. i freshly installed vanilla windows 11 build 22000.318 just to test this. result is the same. match folder is not checked. but they are there all the time.

![image](https://user-images.githubusercontent.com/93516630/141285292-790bede2-6d21-49b8-89c0-626948a66423.png)

**Comment by CrypticCus** [comment]
also v1.3.1 installs seperately. not on previous version. the folder names are changed maybe thats why u are having problem to reproduce?

**Comment by CrypticCus** [comment]
Tested on fresh configured VM with Windows 11 Pro Build 22000.318 x64 EN_US
result same. match folder is ignored everything is always visible

**Comment by ikas-mc** [comment]
[ContextMenuCustomPackage_1.3.2.0_Test.zip](https://github.com/ikas-mc/ContextMenuForWindows11/files/7522771/ContextMenuCustomPackage_1.3.2.0_Test.zip)

I spent some time debugging and may have found the problem,....try to fix it. 
thanks for testing

**Comment by CrypticCus** [comment]
Yup its fixed. thank you for taking care of it.

**Comment by ikas-mc** [comment]
set folder as default
