### ISSUE TITLE
Entry opens msys in parent directory

### ISSUE THREAD

**Issue by sgachoud** [ikas-mc/ContextMenuForWindows11#70]
Hello, I have tried to create an entry to open msys but it opens with the parent directory instead.

For instance, if I try to open msys in "C:/this/that/there", "pwd" in the resulting msys terminal would show "C:/this/that" instead of "C:/this/that/there" as expected.

**Comment by ikas-mc** [comment]
Currently

the parent folder of the selected file will be set as the work path 

so we need to pass the file path as param

 work path is a new feature and may need to be improved

**Comment by sgachoud** [comment]
Sorry, I am not sure I understand. Are you saying that there is a workaround for now and that future versions might integrate a fix for those cases?

**Comment by ikas-mc** [comment]
need to pass in the absolute path yourself
eg:

xxx {parent}/{name}
