### ISSUE TITLE
区别目录和目录背景

### ISSUE THREAD

**Issue by ghost** [ikas-mc/ContextMenuForWindows11#71]
能否让菜单只在右键目录背景时显示  
或者只在右键文件夹时显示

bandizip就可以做到
![image](https://user-images.githubusercontent.com/104875469/213616447-13f96035-a480-4962-ba04-5cfef1c19869.png)
![image](https://user-images.githubusercontent.com/104875469/213616462-228ea1ad-152a-41b4-9e5f-279ab0aacdff.png)

**Comment by ikas-mc** [comment]
这个可能不会加入..有些棘手的问题

**Comment by ikas-mc** [comment]
最新版本已经加入了
