### ISSUE TITLE
my [.c] files are identified as the [.cpp] files

### ISSUE THREAD

**Issue by HOJN008** [ikas-mc/ContextMenuForWindows11#73]
![image](https://user-images.githubusercontent.com/72798536/215287896-d2d34fd7-987a-4e70-9d8b-5a485ba08ccf.png)
![image](https://user-images.githubusercontent.com/72798536/215288107-10cbff6d-02f5-4684-b9c9-e27a037419ad.png)
> **The imgs above are configurations of the app.**
> **The 2nd "GCC[compile]" config are only configured to match .c file only,**
> **but my .c file are still identified as a .cpp file while my cpp files are as normal.**
(The two json files are not the same name,they just have the same title.)
--------------

right click a .c file:
![image](https://user-images.githubusercontent.com/72798536/215287849-620a75a1-e7b3-425f-b122-b2d93ad84a5e.png)
right click a .cpp file
![image](https://user-images.githubusercontent.com/72798536/215288300-da566621-d1d9-4ca6-8219-db9ac969e92e.png)

**Comment by Luk164** [comment]
It seems it matches a substring instead of comparing the extension directly?

**Comment by ikas-mc** [comment]
It is indeed a bug...😥

I will try to fix it in the next version

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.0.0.0
