### ISSUE TITLE
The GUI size of ContextMenu will change

### ISSUE THREAD

**Issue by coswvw** [ikas-mc/ContextMenuForWindows11#77]
The GUI size of ContextMenu stretches from one size to another, and it looks like a flicker or software repaint. This bug only happens when we right-click for the first time, and it won’t happen when we right-click again in a short time.

My PC Information: Xiaomi Book Pro 16 2022 and Windows 11 Pro 22621.1265

Thanks!

**Comment by ikas-mc** [comment]
It should be a bug of windows itself😢
