### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by CrypticCus** [ikas-mc/ContextMenuForWindows11#8]
ability to to add nex>context menu items for example notepad adds itself like this

inside C:\Program Files\WindowsApps\Microsoft.WindowsNotepad_10.2103.7.0_x64__8wekyb3d8bbwe\appxmanifest.xml there is this line that adds .txt to that menu

             <uap:FileType uap4:ShellNewFileName="Assets\NewTextDocument.txt" uap4:ShellNewDisplayName="ms-resource:Resources/ShellNewDisplayName_Txt">.txt</uap:FileType>

and maybe a remove option for existing ones? your app can scan appxmanifest files for line starting with shellnewfilename thingy

**Comment by ikas-mc** [comment]
The main problem is that the current menu registration is not the simple way before.. So it becomes difficult and uncontrollable
