### ISSUE TITLE
如何增加 git bash here的菜单按钮

### ISSUE THREAD

**Issue by zeng865170091** [ikas-mc/ContextMenuForWindows11#83]
### 描述问题

我想创建一个git bash here的按钮，但是我不会设置参数

### 复现步骤
这是我的配置
{"title":"Git Bash Here","exe":"\"D:\\Program Files\\Git\\git-bash.exe\"","param":"\"{path}\"","icon":"\"D:\\Program Files\\Git\\git-bash.exe\",0","acceptExts":"*","acceptDirectory":true,"acceptFile":true,"acceptMultipleFilesFlag":1,"pathDelimiter":"","paramForMultipleFiles":"","index":3}

### 期望结果

能够正确的打开一个gitbash的窗口，且运行的位置是我当前想要打开的位置

### 实际结果

当我在桌面点击按钮时出现的错误：

bash: D:\SystemFolder\Desktop: Is a directory
/usr/bin/bash: Exit 126.

### 系统环境

- 操作系统: win11
- 软件版本:  微软商店下载的免费版本

**Comment by ikas-mc** [comment]
参数错了,如下写
```
--cd="{path}"
```


```json
{
    "title":"Git bash here",
    "exe":"\"C:\\Program Files\\Git\\git-bash.exe\"",
    "param":"--cd=\"{path}\"",
    "icon":"\"C:\\Program Files\\Git\\git-bash.exe\",0",
    "acceptExts":"",
    "acceptDirectory":true,
    "acceptFile":false,
    "acceptMultipleFilesFlag":0,
    "pathDelimiter":"",
    "paramForMultipleFiles":"",
    "index":0
}

```
