### ISSUE TITLE
Feature request: Add preset lists for file extensions

### ISSUE THREAD

**Issue by rubenalamina** [ikas-mc/ContextMenuForWindows11#84]
It would be great to have a list of presets for file extensions so we don't need to typen them every time. Examples would be Image Files (JPG, PNG, BMP, etc), Audio Files (MP3, WAV, M4A, FLAC, etc), Video Files (MKV, MP4, AVI, TS, etc), Document Files (office type extensions), Text Files, Code File and maybe other preset lists. Having the option to add to these would be great as well so we just select the file type and then just add any that are missing and we want to trigger the context menu on.

If this is implemented, I'm sure me and others could provide extension lists to add to the presets if needed.

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.0.0.0
added a link button 

https://github.com/ikas-mc/ContextMenuForWindows11/wiki/File%E2%80%90Extensions
