### ISSUE TITLE
Need help adding same parameter as the original context menu but it is not working

### ISSUE THREAD

**Issue by anandisrocking007** [ikas-mc/ContextMenuForWindows11#85]
I am finding out the location and parameter for the old context menu and adding it to the windows 11 context menu. Althought the softwares are getting activated but the file/folder it was suppose to open with is does not i belive i am doing something wrong with parameter. I am trying to add vscode, open command command line in this folder, avast, lockhunter, openhashtab softwares. Also how do you add context menu when it is linked to a .dll file like in avast.Any help is appreciated....

![VScode](https://user-images.githubusercontent.com/20499472/230012766-c97d5654-45c8-4c44-af83-f38642b1db40.jpg)
![Hash](https://user-images.githubusercontent.com/20499472/230012791-bde43953-e3bf-4241-
![cmd](https://user-images.githubusercontent.com/20499472/230012807-ccf9c9a0-fd50-4857-8d0a-9911c9ce7861.jpg)
b4d1-2cefdc8782c3.jpg)
![lockhunter](https://user-images.githubusercontent.com/20499472/230012824-030de07d-492b-4e0d-9478-129ad1623cb7.jpg)

**Comment by ikas-mc** [comment]
does not support V% or 1%

"%V"  ->  **"{path}"**

![1](https://user-images.githubusercontent.com/65895428/230016527-9a403382-7f75-41f0-a7aa-c9bf39cf40cd.png)

**Comment by Mingtha** [comment]
> does not support V% or 1%
> 
> "%V" -> **"{path}"**
> 
> ![1](https://user-images.githubusercontent.com/65895428/230016527-9a403382-7f75-41f0-a7aa-c9bf39cf40cd.png)

The shortcut file: .lnk, can't be recongnized as a real file address
