### ISSUE TITLE
Help creating "New Text Document" entry

### ISSUE THREAD

**Issue by teijiIshida** [ikas-mc/ContextMenuForWindows11#86]
Hello, I'm trying to do right-click > New Text Document (directly), without going to right-click > New > New Text Document. 

Is this possible with your program?

**Comment by ikas-mc** [comment]
No
Unless you provide an exe that creates the file, then checks it and prompts to rename it
You can also use a script to create a file or just copy form a template file, However, this is not good

**Comment by teijiIshida** [comment]
Thank you for the reply.
