### ISSUE TITLE
扩展名匹配问题

### ISSUE THREAD

**Issue by Ace-Radom** [ikas-mc/ContextMenuForWindows11#89]
我并不清楚这是一个bug还是本来就是这样的 但我注意到扩展名匹配有时的行为和我的预想有出入

<img width="1124" alt="image" src="https://github.com/ikas-mc/ContextMenuForWindows11/assets/104905842/5bc64eca-3382-4960-b7e6-9ba2021f2205">

我尝试让他只匹配 `.json` 文件 在大多数时候他也是有用的 但在遇到我右键点击那些仅扩展名 (如 `.gitignore`) 或无扩展名 (如 `README`) 之类的文件时 他一样会显示这个配置 我不知道这是为什么

**Comment by ikas-mc** [comment]
这个是因为c++ filesystem对于这样的文件,返回的扩展名是""
当前如果扩展名是空,则默认匹配所有菜单
https://en.cppreference.com/w/cpp/filesystem/path/extension
```
<< fs::path("/foo/.hidden").extension() << '\n' 

""
```
==
后面看下是否单独处理

**Comment by ikas-mc** [comment]
最新版本,保留这种模糊匹配的方式,然后加了精确匹配

**Comment by ikas-mc** [comment]
因为功能已经变更,如果有新的问题,可以开新单了..
