### ISSUE TITLE
如何创建单页而不是多页标签？

### ISSUE THREAD

**Issue by weujieytt** [ikas-mc/ContextMenuForWindows11#9]
不需要Custom Menu多选页，我想直接右键能打开vscode而不是还需选择，这样还不如直接”展示更多选项“
![image](https://user-images.githubusercontent.com/70327097/141615557-d42165e8-647a-4108-b669-7cc54577d49e.png)

**Comment by ikas-mc** [comment]
一个应用只能有一个菜单.....这是win11的限制
