### ISSUE TITLE
win11 build 22621.1848 not work again

### ISSUE THREAD

**Issue by luojunyuan** [ikas-mc/ContextMenuForWindows11#91]
我所有的设备全部被微软升级为了 22621.1848，然后所有的Custom Context Menu都失效了。。

**Comment by Hailaylin** [comment]
我也是，现在失效了，难蹦，还以为是自己配置的问题，用的是最新版的
* 操作系统版本 win11 22621.1105
* 软件版本 3.5.0（最新release）
是不是微软API变了还是啥的（咱也不懂）

**Comment by Root18** [comment]
Me too, the Custom Context Menu is not showing up

- OS version win 11 Pro Build 22621.2023
- SW version 3.5.0

**Comment by Crownzhu** [comment]
Me too, the Custom Context Menu is not showing up

OS version win 11 Pro Build 22621.2215
SW version 3.5.0

**Comment by Crownzhu** [comment]
> Me too, the Custom Context Menu is not showing up
> 
> OS version win 11 Pro Build 22621.2215 SW version 3.5.0

已解决，原因在于match file栏不能留空，填上*即可

**Comment by Root18** [comment]
> 已解决，原因在于match file栏不能留空，填上*即可

Thanks, it's working now :)

**Comment by ikas-mc** [comment]
目前没有遇到新版本windows不支持的情况,一般是菜单配置问题或者系统抽风,系统抽风重启任务管理/再不行卸载重装....
