### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by accountnujen** [ikas-mc/ContextMenuForWindows11#93]
What do I need to do to add a refresh button as it was before
![Снимок экрана 2023-07-30 001520](https://github.com/ikas-mc/ContextMenuForWindows11/assets/91395439/46aa75ff-2e22-422c-82da-8bc7d5912ab8)

**Comment by zzahkaboom24** [comment]
The refresh button is already there by default

![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/42496614/b0371848-e7ec-472e-bb0e-3270e478978f)

**Comment by sontopo** [comment]
> The refresh button is already there by default
> 
> ![image](https://private-user-images.githubusercontent.com/42496614/260262074-b0371848-e7ec-472e-bb0e-3270e478978f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDU5MDEsIm5iZiI6MTcwOTU0NTYwMSwicGF0aCI6Ii80MjQ5NjYxNC8yNjAyNjIwNzQtYjAzNzE4NDgtZTdlYy00NzJlLWJiMGUtMzI3MGU0Nzg5NzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5NDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYmYyZjZmODdlODU1NzA5ZDQ2MGM3NzU5ZWQxNjQyY2I0NzRiMWVlMWQ0ZTJkMDlkNDhlNDdlZDA4MjNmMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6B6TIwaUgySBywxsWzcpVoGOP2NwUOni0hl2q6qx79o)

This only applies for Desktop and not when you right click inside a folder.
