### ISSUE TITLE
使用此文件的进程PowerToys.FileLocksmithUI

### ISSUE THREAD

**Issue by hupo376787** [ikas-mc/ContextMenuForWindows11#94]
请教i一下，这个添加了，没有还是不能用这个打开，怎么修改，谢谢
![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/14960168/87463d68-cc26-4cf5-8ff2-4d4a123d59d5)

![image](https://github.com/ikas-mc/ContextMenuForWindows11/assets/14960168/da4b8afc-8147-4aad-937c-a652b68e2705)

**Comment by ikas-mc** [comment]
应该是FileLocksmithUI.exe不支持传递文件参数
通常可以使用任务管理器[命令行] 列查看详细的执行参数

**Comment by luojunyuan** [comment]
你应该先自己尝试确定能工作再添加到customcontextmenu
