### ISSUE TITLE
Not seeing context menu for 3.8.0.0

### ISSUE THREAD

**Issue by InterClaw** [ikas-mc/ContextMenuForWindows11#95]
I installed the Dev version of 3.8.0.0. Then I copied over the custom commands from my 3.5.0.0 install. I can open the UI for 3.8.0.0 and see the custom commands in there.

But I'm not seeing the menu from 3.8.0.0. I only see the previous version. How do I make it show the new version?

**Comment by ikas-mc** [comment]
@InterClaw 
I tested it, and no problem. 
Have you restarted the explorer?

**Comment by InterClaw** [comment]
Ah, that was an easy fix! Embarrassing.

Now I have two menus. Guess I can uninstall 3.5.0.0. :)
