### ISSUE TITLE
Menu not showing

### ISSUE THREAD

**Issue by handcraftedcc** [ikas-mc/ContextMenuForWindows11#97]
Installed it from Microsoft Store
Added Menu items, but nothing is showing. Restarted Explorer and Windows as well, nothing...
Am I missing something?

**Comment by ikas-mc** [comment]
No special settings required


Try this menu example 
[16.debug.zip](https://github.com/ikas-mc/ContextMenuForWindows11/files/12756424/16.debug.zip)

1.download this and unzip   then copy "16.debug.json" to menu folder
2.disable cache

**Comment by ikas-mc** [comment]
@menotuu 
Which package is used?

7061touchwp.CustomContextMenu_3.8.0.0_neutral_._m9vp3t2f55f5t.Msixbundle
ContextMenuCustomDevPackage_3.8.0.0_Test.zip
ContextMenuCustomGithubPackage_3.8.0.0_Test.zip

--
I tested all packages on other computers, installed, restarted Explorer, added menus, and  all OK

**Comment by PJ-Leyden** [comment]
Same issue as the others. I have the 7061touchwp.CustomContextMenu_3.8.0.0_neutral_._m9vp3t2f55f5t.Msixbundle package installed.
