### ISSUE TITLE
建议：是否可以提供一个不包含文件后缀名的{path}

### ISSUE THREAD

**Issue by Faith-YSQ** [ikas-mc/ContextMenuForWindows11#98]
最近想要给7zip添加一个解压到文件夹右键，但是在新建文件夹时如果有后缀名会导致创建失败

**Comment by ikas-mc** [comment]
下次更新 应该可以加上 

目前可以使用powershell脚本处理
```
[System.Diagnostics.Process]::Start('"C:\Program Files\7-Zip\7zG.exe"',  '"x "{path}" -o"{parent}\' +[System.IO.Path]::GetFileNameWithoutExtension('"{name}"') + '"')
```

[7z Extract.zip](https://github.com/ikas-mc/ContextMenuForWindows11/files/12811467/7z.Extract.zip)

**Comment by ikas-mc** [comment]
与https://github.com/ikas-mc/ContextMenuForWindows11/issues/99 合并
测试版已经加上了,actions编译版本
