### ISSUE TITLE
Feature request: File name without extension

### ISSUE THREAD

**Issue by DSplawski92** [ikas-mc/ContextMenuForWindows11#99]
I would be nice to have file name (without extension) param or extract it somehow from existing {name} param.

For example if I would like to extract archive file to the folder with the same name as extracted file.
Currently it is not possible, because it tries to create folder with exact name as archive which is not possible.

**Comment by ikas-mc** [comment]
will add next version...



a temporary workaround

powershell
```
[System.Diagnostics.Process]::Start('"C:\Program Files\7-Zip\7zG.exe"',  '"x "{path}" -o"{parent}\' +[System.IO.Path]::GetFileNameWithoutExtension('"{name}"') + '"')
```
https://github.com/ikas-mc/ContextMenuForWindows11/files/12811467/7z.Extract.zip

**Comment by ikas-mc** [comment]
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.0.0.0
